### ISSUE TITLE
Insights excel export problem: report_run_id field is private but needed for excel downloads.

### ISSUE THREAD

**Issue by benjamin-schaefer** [facebook/facebook-php-business-sdk#170]
Hello, 
I want to export my insights into a cls / xls file. For this, I found the following article:
https://developers.facebook.com/docs/marketing-api/insights/v2.5#export-async-report

I used "getInsightsAsync" to get the data, explained here: https://developers.facebook.com/docs/marketing-api/insights/v2.5#create-async-jobs

So now my question is: How can I get the "report_run_id", necessary for the export?

Regards, Benjamin

**Comment by duliomatos** [comment]
@benjamin-schaefer I see you point: using getInsightsAsync() result you can't get the field report_run_id as it is private, as it is handled behind the scene. But for excel downloads, which is not a graph api request you need to use it. Changing the description of the issue, I'll have to think of the best way to approach it. If you are in a hurry, you can get report result as json.

**Comment by benjamin-schaefer** [comment]
Ah, okay. What would be the recommended way to export insights? Could you please give a short example, starting with a campaign object? Thanks a lot!

**Comment by duliomatos** [comment]
@benjamin-schaefer, how are you? A simple example, that returns the insights in json format, would be this one:

```php
use FacebookAds\Object\AdAccount;
use FacebookAds\Object\Fields\InsightsFields;
use FacebookAds\Object\Values\InsightsBreakdowns;
use FacebookAds\Object\Values\InsightsOperators;
$account = new AdAccount($ad_account_id);

$params = array(
  'breakdowns' => array(
    InsightsBreakdowns::AGE,
    InsightsBreakdowns::GENDER,
  ),
  'filtering' => array(
    array(
      'field' => 'campaign.name',
      'operator' => InsightsOperators::CONTAIN,
      'value' => '18-25',
    ),
  ),
);

$stats = $account->getInsights(array(), $params);
```

**Comment by duliomatos** [comment]
@benjamin-schaefer, closing this. For a campaign the code is very much the same just change the object that calls `getInsights`. Best!

```php
use FacebookAds\Object\Campaign;
use FacebookAds\Object\Values\InsightsBreakdowns;

$campaign = new Campaign($campaign_id);

$params = array(
  'breakdowns' => array(
    InsightsBreakdowns::AGE,
    InsightsBreakdowns::GENDER,
  ),
);

$insights = $campaign->getInsights(array(), $params);
```

**Comment by benjamin-schaefer** [comment]
@duliomatos thank you for your example. But my problem is still how to get report_run_id for exporting the data. Hope you can help.

**Comment by duliomatos** [comment]
@benjamin-schaefer Reopening, I'll looking into changing the SDK to make this field public or maybe exporting the excel URL.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
