### ISSUE TITLE
Using ETags

### ISSUE THREAD

**Issue by loncar** [facebook/facebook-php-business-sdk#197]
Is there any way to add ETag hash to request like there is on [standard sdk](https://developers.facebook.com/docs/php/FacebookRequest/5.0.0#overview) ?

**Comment by duliomatos** [comment]
Hello Ioncar, we definitely need to support it in a similar way, I'll keep this open as a feature request.

**Comment by kenbing** [comment]
Hello duliomatos, can't wait to see the new release supported using etag!

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
