### ISSUE TITLE
Fix adgroup_creation.php

### ISSUE THREAD

**Issue by jeliasson** [facebook/facebook-php-business-sdk#211]
Hey all,

Having tried release 2.5.0, 2.5.2 and 2.6.0; I get the following error upon trying to create an Ad.
"Your ads couldn't be created for the following reason: You must include the required field 'status'".

Adding the 'STATUS' constant to 'status' in AdSets won't do the trick.
Bug report with lack of reply: https://developers.facebook.com/bugs/434655563408601/

**Comment by jeliasson** [comment]
Per example on https://github.com/facebook/facebook-php-ads-sdk/blob/master/examples/adgroup_creation.php#L186

```php
$ad = new Ad(null, $account->id);
$ad->setData(array(
  AdFields::CREATIVE => array('creative_id' => $creative->id),
  AdFields::NAME => 'My First Ad',
  AdFields::ADSET_ID => $adset->id,
));

$ad->create();
echo 'Ad ID:' . $ad->id . "\n";
```

**Comment by duliomatos** [comment]
Hey @jeliasson, sorry these examples may not be as up to date as our documentation in our developers portal, please follow our code examples here: https://developers.facebook.com/docs/marketing-api/reference/adgroup. 
I'll change the title to reflect that the code https://github.com/facebook/facebook-php-ads-sdk/blob/master/examples/adgroup_creation.php#L186 here should be fixed.

**Comment by duliomatos** [comment]
Should make these examples to run as unit tests if we are to keep them.

**Comment by goodwintheus** [comment]
Hi there folks,

I'm really new on here and I was wondering if you might be able to help me out. I run a small cinema in New Zealand and we are trying to set up our adverts on Facebook so they activated/deactivated based on real time weather. There are many online weather companies that provide an API- currently using weather triggers like that for google, but I can't for the life of me figure of how to do it on Facebook. I really appreciate you help and anything to get me started/in the right direction would be a huge help.

Thanks,

Theus

**Comment by duliomatos** [comment]
@goodwintheus, to learn how to use our Marketing API's please refer to our developers site https://developers.intern.facebook.com/docs/marketing-apis
and try our Graph Academy course: https://developers.facebook.com/graph-academy

**Comment by wildwestriverrider** [comment]
Hopefully this will save people some time.  I was having the same issue.
```
$ad->setData(array(
  AdFields::NAME => 'My Ad',
  AdFields::ADSET_ID => $this->ad_set->id,
  AdFields::STATUS => Ad::STATUS_PAUSED,
  AdFields::CREATIVE => array(
  'creative_id' => $this->creative->id,
 )
));
```
Not having the Ad Status was my issue.

**Comment by bartclaeys** [comment]
Uh this is frustrating, please remove the sample code if it's out of date... Stop wasting people's time.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
