### ISSUE TITLE
Cannot determine the target object for this request

### ISSUE THREAD

**Issue by AinSynagoga** [facebook/facebook-php-business-sdk#213]
I have created a system user and I am using its access token to get some campaign insights, However I am getting a 
'Uncaught exception 'FacebookAds\Http\Exception\PermissionException' with message '(#275) Cannot determine the target object for this request.'

Even though the campaign id I use is existing. What could be the issue?

**Comment by duliomatos** [comment]
Hey @AinSynagoga, sorry for the delay. Can you share the code for the calls you're making? (minus any private info of course). Thx!

**Comment by SuecoMarcus** [comment]
@duliomatos Hi! I have a very similar problem.

This is part of my code:
```php
$account = new AdAccount($account_id);
$async_job = $account->getInsightsAsync(
    array(),
    array(
        'level' => 'adset',
        'time_increment'	=> 'all_days',
        'time_ranges' 		=> array(
            $time_range,
        ),
        'fields' => array(
            InsightsFields::CAMPAIGN_ID,
            InsightsFields::CAMPAIGN_NAME,
            InsightsFields::ADSET_ID,
            InsightsFields::ADSET_NAME,
            InsightsFields::UNIQUE_CLICKS,
            InsightsFields::SPEND,
            InsightsFields::IMPRESSIONS,
            InsightsFields::INLINE_LINK_CLICKS, 
	)
    )
);
				
sleep(1);
$async_job->read();
					
while (!$async_job->isComplete()) {
    sleep(1);
    $async_job->read();
}

$insights = $async_job->getInsights();
$insights->setUseImplicitFetch(true);

foreach($insights as $insight) {
    // Some more code...
}
```

This piece of code works sometimes... but I mostly get these two errors: 

- [FacebookAds\Http\Exception\AuthorizationException] - 275 - Cannot determine the target object for this request. Currently supported objects include ad account, business account and associated objects.

- [FacebookAds\Http\Exception\AuthorizationException] Error accessing adreport job.

Thank you!

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
