### ISSUE TITLE
Use of multiple access tokens on CRUD objects bug

### ISSUE THREAD

**Issue by kianandersson** [facebook/facebook-php-business-sdk#220]
I am currently developing an app which collects insights from multiple account with diffrent access tokens. I found that when using the getInsightsAsync method in the PHP SDK on multiple AdAccount's with diffrent Api objects (with diffrent access tokens) i got a permission error.

I looked around in the code of the SDK and found that when the AdAccount object initializes the ApiRequest it does not fill out any parameters which makes the ApiRequest object use the default Api object rather that the one used when initializing the AdAccount object.

This i fixed by replacing "new AdReportRun()" with "new AdReportRun(null, null, $this->api)" in FacebookAds\Object\AdAccount on line 1287.

I would therefore suggest You to make sure to reuse the api-parameter when initializing new CRUD objects inside other objects.

I hope my description was understandable. If not please do not hesitate to write me back.

**Comment by duliomatos** [comment]
Hello @kianandersson, thanks for reporting. To understand a little better can you share a code example (removing any sensitive info)?

**Comment by duliomatos** [comment]
@kianandersson, lmk if you can share some example code of this flow ;-)

**Comment by kianandersson** [comment]
Hi @duliomatos, sorry for the delayed response.

The use of multiple accounts with different tokens:
![use](https://cloud.githubusercontent.com/assets/20352633/19303292/5d3b85f6-9068-11e6-8449-33849d8e919a.png)

Before edit in FacebookAds\Object\AdAccount
![before](https://cloud.githubusercontent.com/assets/20352633/19303297/60159f32-9068-11e6-9483-b04898058bb8.png)

After edit in FacebookAds\Object\AdAccount
![after](https://cloud.githubusercontent.com/assets/20352633/19303300/620f371c-9068-11e6-866f-db998290607c.png)

**Comment by kianandersson** [comment]
https://github.com/facebook/facebook-php-ads-sdk/blame/master/src/FacebookAds/Object/AdAccount.php#L1287

I am not sure if this is stil a problem in newer versions of the SDK

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
