### ISSUE TITLE
Fix copyrights

### ISSUE THREAD

**Issue by AloneCoder** [facebook/facebook-php-business-sdk#232]
Hey!

I think you have some typos in copyright sections 

Api.php

```
Copyright (c) 2014-present, Facebook, Inc. All rights reserved.
```

ApiConfig.php

```
Copyright (c) 2015-present, Facebook, Inc. All rights reserved.
```

ApiRequest.php has no copyright section

You can find out more examples

**Comment by duliomatos** [comment]
Thx @AloneCoder for being so helpful! I'll fix it :-)

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
