### ISSUE TITLE
AbstractObject's exportData function overridden

### ISSUE THREAD

**Issue by allentsai** [facebook/facebook-php-business-sdk#234]
We should have some way to call the `AbstractObject`'s `exportData` function from more classes.  Right now, `AbstractCrudObject` overrides `exportData` to only export `changedFields` values, so the only way we can get back clean data for anything extending `AbstractArchivableCrudObject` is via `getData` and cleaning the data ourselves.

Definitely a nice-to-have rather than a need-to-have.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
