### ISSUE TITLE
CustomAudience::createUser does not properly pass Api to User.

### ISSUE THREAD

**Issue by kellegous** [facebook/facebook-php-business-sdk#235]
If you create a `CustomAudience` by passing in an `Api` in the constructor, that api object is not retained in `createUser` when a new `User` crud object is instantiated.

Example:

```
/* @var FacebookAds\Api $api */
$api = ...;
$audience = new CustomAudience(null, $account_id, $api);
$audience->createUser(....);
```

An exception is thrown as a result of this [line](https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/CustomAudience.php#L257). The issue is that a child Crud Object is created without passing the `$api`.

I suspect this line should instead be:
`new User(null, null, $this->api)`

This is not the only place in this file that creates a sub-object without passing the Api.
https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/CustomAudience.php#L280
https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/CustomAudience.php#L338
https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/CustomAudience.php#L110

**Comment by duliomatos** [comment]
Hey @kellegous, thx for reporting this. I'll work on this and in addition verify if this issue may affect other classes as well.

**Comment by angiehypergrowth** [comment]
Hi, is there any updates regarding this, as we experienced the same thing

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
