### ISSUE TITLE
Include `blame_field` to RequestException

### ISSUE THREAD

**Issue by allentsai** [facebook/facebook-php-business-sdk#237]
I think there is a bug with how RequestException is being generated:

```
$error_data = static::getErrorData($response->getContent());
...
$this->errorBlameFieldSpecs = $error_data['error_blame_field_specs'];
```

getErrorData contains the following:

```
      'error_blame_field_specs' =>
        static::idx(static::idx($error_data, 'error_data', array()),
          'blame_field_specs'),
```

However, an error response from Graph Explorer returns me:

```
{
  "error": {
    "message": "Invalid parameter",
    "type": "OAuthException",
    "code": 100,
    "error_data": {
      "blame_field": "targeting"
    },
    "error_subcode": 1487126,
    "is_transient": false,
    "error_user_title": "Invalid Placement",
    "error_user_msg": "Invalid Placement",
    "fbtrace_id": "FYm+yVA1pER"
  }
}
```

note `blame_field` vs `blame_field_specs`.

This is in the context of ad set creation.  I have not tried reproducing the issue elsewhere, so it is possible that the Graph API does not return the same error response for all endpoints, though I believe this to be unlikely

**Comment by duliomatos** [comment]
Hey @allentsai, thx for digging this. Actually `blame_field` comes in addition to `blame_field_specs`, the former is for when a simple field name suffices to identify the error location. Adding this as a feature request.

**Comment by jingping2015** [comment]
This feature request doesn't appear to be actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
