### ISSUE TITLE
Issue with CApath/file when loading with php sdk v5

### ISSUE THREAD

**Issue by immarina** [facebook/facebook-php-business-sdk#239]
Hi guys, im getting a really weird error that im hoping someone knows what to do with :(

So im installing php-ads-sdk v2.7.1 and php-sdk-v4 v5.0 through composer as recommended
However, when both of them are loaded by the same autoload whenever I try to make API calls im getting an exception: error setting certificate verify locations: CApath: none CAfile:/

However, if i install both the SDKs on separate composer folders, IE not the same autoload file the problem seems to go away.

Any clue as to what to do here?

**Comment by duliomatos** [comment]
@immarina, thx for reporting. Can you share your `composer.json` and the PHP version? Which of the two API's and which call did you try?

**Comment by immarina** [comment]
Sure thing, composer.js:
`{
    "require": {
        "facebook/php-sdk-v4": "^5.2",
        "facebook/php-ads-sdk": "2.7.1"
    }
}`

PHP version: 5.5
The call I made was $me->getAdAccounts with the following fields:

`$fields = array(
            AdAccountFields::ACCOUNT_ID,
            AdAccountFields::ACCOUNT_STATUS,
            AdAccountFields::AMOUNT_SPENT,
            AdAccountFields::BALANCE,
            AdAccountFields::DISABLE_REASON,
            AdAccountFields::LAST_USED_TIME,
            AdAccountFields::NAME,
            AdAccountFields::OWNER
        );`

I think its worth mentioning that the php-sdk is loaded first and creates a new Facebook\Facebook object with the app id, secret and graph version 2.7. Also, a redirectLoginHelper is created - none of this fails to be executed.
