### ISSUE TITLE
Issues in ad creating on step-7

### ISSUE THREAD

**Issue by divsbhalala** [facebook/facebook-php-business-sdk#240]
Below is the my code  for creating ad and i an getting error on step-7

 public function add_ads($account_id,$campaign_id){
        /**
         \* Step 3 Search Targeting
         */
        $results = TargetingSearch::search(
          $type = TargetingSearchTypes::INTEREST,
          $class = null,
          $query = 'facebook');

```
    // we'll take the top result for now
    $target = (count($results)) ? $results->current() : null;

    echo "Using target: ".$target->name."\n";
    print_r($target);

    $targeting = new TargetingSpecs();
    $targeting->{TargetingSpecsFields::GEO_LOCATIONS}
      = array('countries' => array('GB'));
    $targeting->{TargetingSpecsFields::INTERESTS} = array(
        array(
            'id' => $target->id,
            'name' => $target->name,
        ),
    );
    print_r($targeting->getData());
    /**
     * Step 4 Create the AdSet
     */
    $adset = new AdSet(null, "act_".$account_id);
    var_dump($account_id);
    //var_dump(expression)
    $adset->setData(array(
        AdSetFields::ACCOUNT_ID => "act_".$account_id,
        AdSetFields::NAME => 'My First AdSet',
        AdFields::BID_TYPE => 'CPC',
        AdSetFields::BID_INFO => array('CLICKS' => 500),
        AdSetFields::CAMPAIGN_ID => $campaign_id,
        AdSetFields::TARGETING => $targeting,
        AdSetFields::OPTIMIZATION_GOAL => AdSetOptimizationGoalValues::REACH,
        AdSetFields::BILLING_EVENT => AdSetBillingEventValues::IMPRESSIONS,
        AdSetFields::BID_AMOUNT => 2,
        AdSetFields::DAILY_BUDGET => 4000,
        AdSetFields::START_TIME =>(new \DateTime("+1 week"))->format(\DateTime::ISO8601),
        AdSetFields::END_TIME =>(new \DateTime("+2 week"))->format(\DateTime::ISO8601),
    ));
    print_r($adset->getData());
    $adset->validate()->create(array(
      AdSet::STATUS_PARAM_NAME => AdSet::STATUS_PAUSED,
    ));

    echo 'AdSet  ID: '. $adset->id . "\n";

    /**
     * Step 5 Create an AdImage
     */

    $image = new AdImage(null, "act_".$account_id);
    $image->{AdImageFields::FILENAME}
      = __DIR__.'/avatar3.jpg';
      print_r($image);
    $image->create();
    echo 'Image Hash: '.$image->hash . "\n";

    /**
     * Step 6 Create an AdCreative
     */


    $creative = new AdCreative(null, "act_".$account_id);
    $creative->setData(array(
      AdCreativeFields::NAME => 'Sample Creative',
      AdCreativeFields::TITLE => 'Welcome to the Jungle',
      AdCreativeFields::BODY => 'We\'ve got fun \'n\' games',
      AdCreativeFields::IMAGE_HASH => $image->hash,
      AdCreativeFields::OBJECT_URL => 'http://www.example.com/',
    ));

    $creative->create();
    echo 'Creative ID: '.$creative->id . "\n";

    /**
     * Step 7 Create an Ad
     */
    $ad = new Ad(null, "act_".$account_id);

   $ad->setData(array(
      AdFields::CREATIVE =>
        array('creative_id' => $creative->id),
      AdFields::NAME => 'My First Ad',
      AdFields::ADSET_ID => $adset->id,
    ));
    print_r($ad);
 $ad->create(array(Ad::STATUS_PARAM_NAME => Ad::STATUS_PAUSED));
    echo 'Ad ID:' . $ad->id . "\n";
    return $ad;
}
```
## Here is the error  which i getting 

Fatal error:  Uncaught FacebookAds\Http\Exception\AuthorizationException: Invalid parameter in /var/www/html/codeigniter_metronic-master/application/libraries/facebook/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:140
Stack trace:
#0 /var/www/html/codeigniter_metronic-master/application/libraries/facebook/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(215): FacebookAds\Http\Exception\RequestException::create(Object(FacebookAds\Http\Response))
#1 /var/www/html/codeigniter_metronic-master/application/libraries/facebook/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request))
#2 /var/www/html/codeigniter_metronic-master/application/libraries/facebook/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(151): FacebookAds\Http\Request->execute()
#3 /var/www/html/codeigniter_metronic-master/application/libraries/facebook/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(193): FacebookAds\Api->executeRe in /var/www/html/codeigniter_metronic-master/application/libraries/facebook/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php on line 140

**Comment by duliomatos** [comment]
Hey @divsbhalala, can you share a `var_dump` of the Exception, or get more detail from the exception by using these methods `getErrorUserMessage`/ `getErrorUserTitle`? The details should explain which field may be the culprit

**Comment by alskaman** [comment]
Hey @duliomatos, I have exactly the same problem as @divsbhalala. Exactly word for word. So I'm just using the example code from your guys' folder. I'm still a beginner with using this sdk (and php in general), so I'm not exactly sure how to go about calling the `getErrorUserMessage` method, but I was able to do a var_dump on the `$ad` variable and this is what comes from it:

`object(FacebookAds\Object\Ad)#76 (5) { ["changedFields":protected]=> array(3) { ["creative"]=> array(1) { ["creative_id"]=> string(13) "6051186189791" } ["name"]=> string(11) "My First Ad" ["adset_id"]=> string(13) "6051189278591" } ["api":protected]=> object(FacebookAds\Api)#3 (4) { ["session":"FacebookAds\Api":private]=> object(FacebookAds\Session)#2 (4) { ["appId":protected]=> string(15) "178028915942255" ["appSecret":protected]=> string(32) "21****************************44" ["accessToken":protected]=> string(187) "EAACh6pZALY28**************5FIO9s1DJfTA6J8u" ["appSecretProof":protected]=> string(64) "85eb9154f********************************************6fac2ad55241" } ["logger":protected]=> object(FacebookAds\Logger\NullLogger)#13 (0) { } ["httpClient":protected]=> object(FacebookAds\Http\Client)#4 (6) { ["requestPrototype":protected]=> object(FacebookAds\Http\Request)#10 (10) { ["client":protected]=> *RECURSION* ["headers":protected]=> NULL ["method":protected]=> string(3) "GET" ["protocol":protected]=> string(8) "https://" ["domain":protected]=> NULL ["path":protected]=> NULL ["graphVersion":protected]=> NULL ["queryParams":protected]=> NULL ["bodyParams":protected]=> NULL ["fileParams":protected]=> NULL } ["responsePrototype":protected]=> object(FacebookAds\Http\Response)#16 (5) { ["request":protected]=> NULL ["statusCode":protected]=> NULL ["headers":protected]=> NULL ["body":protected]=> NULL ["content":protected]=> NULL } ["defaultRequestHeaders":protected]=> object(FacebookAds\Http\Headers)#18 (1) { ["storage":"ArrayObject":private]=> array(2) { ["User-Agent"]=> string(14) "fb-php-ads-2.7" ["Accept-Encoding"]=> string(1) "*" } } ["adapter":protected]=> object(FacebookAds\Http\Adapter\CurlAdapter)#14 (3) { ["curl":protected]=> object(FacebookAds\Http\Adapter\Curl\Curl55)#15 (1) { ["handle":protected]=> resource(32) of type (curl) } ["opts":protected]=> object(ArrayObject)#19 (1) { ["storage":"ArrayObject":private]=> array(5) { [78]=> int(10) [13]=> int(60) [19913]=> bool(true) [42]=> bool(true) [10065]=> string(109) "/Library/WebServer/Documents/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/../../../fb_ca_chain_bundle.crt" } } ["client":protected]=> *RECURSION* } ["caBundlePath":protected]=> string(109) "/Library/WebServer/Documents/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/../../../fb_ca_chain_bundle.crt" ["defaultGraphBaseDomain":protected]=> string(12) "facebook.com" } ["defaultGraphVersion":protected]=> string(3) "2.7" } ["parentId":protected]=> string(19) "act_119035785170348" ["data":protected]=> array(27) { ["account_id"]=> NULL ["ad_review_feedback"]=> NULL ["adlabels"]=> NULL ["adset"]=> NULL ["adset_id"]=> string(13) "6051189278591" ["bid_amount"]=> NULL ["bid_info"]=> NULL ["bid_type"]=> NULL ["campaign"]=> NULL ["campaign_id"]=> NULL ["configured_status"]=> NULL ["conversion_specs"]=> NULL ["created_time"]=> NULL ["creative"]=> array(1) { ["creative_id"]=> string(13) "6051186189791" } ["effective_status"]=> NULL ["id"]=> NULL ["last_updated_by_app_id"]=> NULL ["name"]=> string(11) "My First Ad" ["recommendations"]=> NULL ["status"]=> NULL ["tracking_specs"]=> NULL ["updated_time"]=> NULL ["date_format"]=> NULL ["display_sequence"]=> NULL ["execution_options"]=> NULL ["redownload"]=> NULL ["filename"]=> NULL } ["_type_checker":protected]=> object(FacebookAds\TypeChecker)#74 (3) { ["type_data":"FacebookAds\TypeChecker":private]=> array(27) { ["account_id"]=> string(6) "string" ["ad_review_feedback"]=> string(21) "AdgroupReviewFeedback" ["adlabels"]=> string(13) "list" ["adset"]=> string(5) "AdSet" ["adset_id"]=> string(6) "string" ["bid_amount"]=> string(3) "int" ["bid_info"]=> string(25) "map" ["bid_type"]=> string(7) "BidType" ["campaign"]=> string(8) "Campaign" ["campaign_id"]=> string(6) "string" ["configured_status"]=> string(16) "ConfiguredStatus" ["conversion_specs"]=> string(27) "list" ["created_time"]=> string(8) "datetime" ["creative"]=> string(10) "AdCreative" ["effective_status"]=> string(15) "EffectiveStatus" ["id"]=> string(6) "string" ["last_updated_by_app_id"]=> string(6) "string" ["name"]=> string(6) "string" ["recommendations"]=> string(22) "list" ["status"]=> string(6) "Status" ["tracking_specs"]=> string(27) "list" ["updated_time"]=> string(8) "datetime" ["date_format"]=> string(6) "string" ["display_sequence"]=> string(12) "unsigned int" ["execution_options"]=> string(16) "ExecutionOptions" ["redownload"]=> string(4) "bool" ["filename"]=> string(4) "file" } ["enum_data":"FacebookAds\TypeChecker":private]=> array(7) { ["BidType"]=> array(5) { [0]=> string(3) "CPC" [1]=> string(3) "CPM" [2]=> string(13) "MULTI_PREMIUM" [3]=> string(13) "ABSOLUTE_OCPM" [4]=> string(3) "CPA" } ["ConfiguredStatus"]=> array(4) { [0]=> string(6) "ACTIVE" [1]=> string(6) "PAUSED" [2]=> string(7) "DELETED" [3]=> string(8) "ARCHIVED" } ["EffectiveStatus"]=> array(10) { [0]=> string(6) "ACTIVE" [1]=> string(6) "PAUSED" [2]=> string(7) "DELETED" [3]=> string(14) "PENDING_REVIEW" [4]=> string(11) "DISAPPROVED" [5]=> string(11) "PREAPPROVED" [6]=> string(20) "PENDING_BILLING_INFO" [7]=> string(15) "CAMPAIGN_PAUSED" [8]=> string(8) "ARCHIVED" [9]=> string(12) "ADSET_PAUSED" } ["Status"]=> array(4) { [0]=> string(6) "ACTIVE" [1]=> string(6) "PAUSED" [2]=> string(7) "DELETED" [3]=> string(8) "ARCHIVED" } ["DatePreset"]=> array(15) { [0]=> string(5) "today" [1]=> string(9) "yesterday" [2]=> string(11) "last_3_days" [3]=> string(9) "this_week" [4]=> string(9) "last_week" [5]=> string(11) "last_7_days" [6]=> string(12) "last_14_days" [7]=> string(12) "last_28_days" [8]=> string(12) "last_30_days" [9]=> string(12) "last_90_days" [10]=> string(10) "this_month" [11]=> string(10) "last_month" [12]=> string(12) "this_quarter" [13]=> string(13) "last_3_months" [14]=> string(8) "lifetime" } ["ExecutionOptions"]=> array(3) { [0]=> string(13) "validate_only" [1]=> string(21) "synchronous_ad_review" [2]=> string(23) "include_recommendations" } ["Operator"]=> array(2) { [0]=> string(3) "ALL" [1]=> string(3) "ANY" } } ["primitive_types":"FacebookAds\TypeChecker":private]=> array(7) { [0]=> string(12) "unsigned int" [1]=> string(3) "int" [2]=> string(4) "bool" [3]=> string(6) "string" [4]=> string(6) "Object" [5]=> string(8) "datetime" [6]=> string(5) "float" } } } `

I've been trying to figure this one problem out for about 2 days strait now. I would be eternally grateful for your help!

**Comment by duliomatos** [comment]
Hey @alskaman, glad to help if I can. I would suggest that even better than the examples folder you checkout our reference docs, we have better examples that are easier to understand of the PHP SDK code: https://developers.facebook.com/docs/marketing-api/reference/v2.7
Given that, what was the example you tried? I'd like to test it and improve it.

**Comment by alskaman** [comment]
The example that I've been working with is `adgroup_creation.php`. I just want to automate the process of putting an ad on Facebook and having it run, and based on all the videos and examples and stuff everyone makes it seem too easy, so I'm assuming it should be easy which makes me wonder if it is like an authentication problem or like do I need to have "Basic" access rather than just "Developer". If I can create an ad and have it run, that is literally all I need.

So in the `adgroup_creation.php` file, I've tried running the code by commenting out lines and testing, and it seems to me that everything works exactly how it should except for this line: `$ad->create();`...if that line is commented out everything is fine, but if it isn't then it throws that error.

I'll keep trying things and take a look at that link you sent me! Thank you so much for your help @duliomatos!

**Comment by avastamin** [comment]
@alskaman, I checked your error log and it's not enough. I recommend you to use `try{
//your code
}catch (Exception $e) {
    var_dump($e);
}`
Your will get specific error message. I fixed my problem in that way.

**Comment by jeskiZhao** [comment]
@alskaman Have you solved this problem? I have the same problem too, but I havn't find the way to solve it. Can you help me?

**Comment by alskaman** [comment]
Sorry @jeskiZhao I was never able to figure it out, so I decided to go a different direction on my project. Sorry I couldn't be of more help.

**Comment by jeskiZhao** [comment]
@alskaman Thanks for your reply.

**Comment by skyfloyd** [comment]
I had same problem and var_dump shows:
["error"]=>
    array(8) {
      ["message"]=>
      string(17) "Invalid parameter"
      ["type"]=>
      string(14) "OAuthException"
      ["code"]=>
      int(100)
      ["error_subcode"]=>
      int(1815520)
      ["is_transient"]=>
      bool(false)
      ["error_user_title"]=>
      string(35) "Ad Creative Does Not Use Valid Link"
      ["error_user_msg"]=>
      string(274) "The link in this ad is either missing or invalid for Link Click Ads optimization.
 This could be because this ad needs to link external content (e.g., an advertiser's website), but this
 ad does not (e.g., it links to a Facebook page). Fix this error by making the link valid."
      ["fbtrace_id"]=>
      string(11) "DffGEgGy8ji"
    }

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
