### ISSUE TITLE
2.7 Lost ability to claim pages for a business manager access

### ISSUE THREAD

**Issue by nikita2206** [facebook/facebook-php-business-sdk#251]
There is no `FacebookAds\Object\Business->claimPage()` method anymore as of 2.7.1 (opposed to [2.6](https://github.com/facebook/facebook-php-ads-sdk/blob/2.6.0/src/FacebookAds/Object/Business.php#L193)). And there seems to be no replacement for it (I'd be happy to be wrong).

**Comment by daphyFB** [comment]
Hi, thanks for pointing this out. You are right; there is claim/add pages under business manager SDK in 2.7.1 (UI is still available though). We're doing some changes on our side and we'll track it to add those features back.

**Comment by nikita2206** [comment]
Great, thank you! in the meantime we will use the old api (with new sdk and manually implemented claim/remove methods) if that's alright

**Comment by daphyFB** [comment]
That should work; please let us know otherwise. Thank you for understanding!

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
