### ISSUE TITLE
Project object Removed

### ISSUE THREAD

**Issue by allentsai** [facebook/facebook-php-business-sdk#257]
In 2.6.1, there was a `Project` object that could that could be created on a business.
`$project = new Project(null, $businessId);`
This object disappeared in v2.7 and 2.8, but this was not mentioned in the change logs.  Additionally, the routes still seem to be available here: https://developers.facebook.com/docs/marketing-api/businessmanager/v2.8 (search Projects)
I'm not sure if the object was removed on accident, or the change was just undocumented.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
