### ISSUE TITLE
Want to use ProductItem::getProductFromCatalogByRetailerId()

### ISSUE THREAD

**Issue by suzuki** [facebook/facebook-php-business-sdk#262]
## Overview
- I want to use these methods:
  - `ProductItem::getProductFromCatalogByRetailerId()`
  - `ProductItem::updateProductInCatalogByRetailerId()`
## Cause
- In Legacy, we can use these methods:
  - `Product::getProductFromCatalogByRetailerId()`
    - https://github.com/facebook/facebook-php-ads-sdk/blob/legacy/src/FacebookAds/Object/Product.php#L59
  - `Product::updateProductInCatalogByRetailerId()`
    - https://github.com/facebook/facebook-php-ads-sdk/blob/legacy/src/FacebookAds/Object/Product.php#L81
- In v2.8 API, we can use this feature
  - https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-catalog

> Update Individual Product
> You can update an individual product's data in real time. To update a product, include the updated fields in an HTTP POST:
> 
> https://graph.facebook.com/catalog:PRODUCT_CATALOG_ID:base64urlencode(retailer_id)
- In v2.8 SDK, `ProductItem` class does not have these useful methods.
  - https://github.com/facebook/facebook-php-ads-sdk/blob/ad5da8006abc9c3498b60b059b4e11285ca5eff1/src/FacebookAds/Object/ProductItem.php
  - Also `Product` class dose not have.
    - https://github.com/facebook/facebook-php-ads-sdk/blob/ad5da8006abc9c3498b60b059b4e11285ca5eff1/src/FacebookAds/Object/Product.php
## Expect
- Imprement above methods to `ProductItem` class.
  - I think that this is not a bug, but SDK has been downgraded.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
