### ISSUE TITLE
AdVideo attempting to access field that doesn't exist

### ISSUE THREAD

**Issue by a-kinder** [facebook/facebook-php-business-sdk#279]
I'm attempting to begin a chunked upload using the [AdVideo](https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/AdVideo.php) object using code similar to this: 

```
      $act_id = "act_" . $this->settings['account_id'];
      $video = new Advideo(null, $act_id);
      $video->{AdVideoFields::SOURCE} = $videoPath;
  
      $params = array('upload_phase' => 'start',
        'file_size' => $size_bytes,
        'access_token' => $this->settings['access_token']);

      $result = $video->create($params);
```

however I get a response saying  "Undefined index: id in Advideo.php on line 74"

looking at line 74 of AdVideo it makes an API request and gets the content of the spot and tries to set data['id'] from the 'id' portion of the response, however when I var_dump the response there is no ID field, there is simply `video_id`, `start_offset`, `end_offset` and `upload_session_id` as is expected with a chunked upload. Here is the offending snippet:

```
$response = $this->getApi()->executeRequest($request);

$data = $response->getContent();
$this->data[static::FIELD_ID] = is_string($data) ? $data : (string) $data[static::FIELD_ID];

```

Is this a mistake? It appears to work when uploading a video in one piece.

**Comment by cloudxu** [comment]
Thank you for reporting. We are investigating it.

**Comment by a-kinder** [comment]
for reference, I was able to find a way to do chunked upload with the following code:

```
 $fb = new Facebook([
        'app_id' => $this->settings['app_id'],
        'app_secret' => $this->settings['app_secret'],
        'default_graph_version' => 'v2.8',
      ]);
      
      $app = new FacebookApp($this->settings['app_id'], $this->settings['app_secret']);
      $accessToken = $this->settings['access_token'] ?: $this->defaultAccessToken;
      $uploader = new FacebookResumableUploader($app, new FacebookClient(), $accessToken, 'v2.8');
      $endpoint = "/act_${act_id}/advideos";
      $file = $fb->videoToUpload($localPath);
      $chunk = $uploader->start($endpoint, $file);
      do {
        echo "chunk\n";
        // use existing implementation maxTriesTransfer or use your own code here
        $chunk = $this->maxTriesTransfer($uploader, $endpoint, $chunk, 3);
      } while (!$chunk->isLastChunk());
      return [
        'video_id' => $chunk->getVideoId(),
        'success' => $uploader->finish($endpoint, $chunk->getUploadSessionId(), []),
      ];
```

However it isn't very clearly documented in the Ads API, I actually found it with the regular Graph video uploads and just changed the request URI to /advideos

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
