### ISSUE TITLE
Cannot add work_employer to audience.

### ISSUE THREAD

**Issue by saad-gh** [facebook/facebook-php-business-sdk#287]
I am using the following code to add a work_employer to the audience

```
$set = new AdSet($ad_set_ID);
$set->{TargetingFields::WORK_EMPLOYERS} = array(array('id' => '58749257416','name' => 'Visit Austin'));
$set->update();
```
But this is giving the following error

> Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message '(#275) Cannot determine the target object for this request. Currently supported objects include ad account, business account and associated objects

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
