### ISSUE TITLE
Issues with AdImage

### ISSUE THREAD

**Issue by asim-masood** [facebook/facebook-php-business-sdk#293]
issue 1:
in file ~/php-ads-sdk/src/FacebookAds/Object/AdImage.php
line 130 & 131 should be flipped over. unset($data[AdImageFields::FILENAME]) should come after $params = array_merge($data, $params);

isseu 2:
This doesn't work:
$image->{AdImageFields::FILENAME} = '/path-to-some-image/13.jpg';

This work:
$image->{AdImageFields::FILENAME} = '@/path-to-some-image/13.jpg';

When solved both issues the image AdImage works.

**Comment by agarwalsudeep** [comment]
For issue 2 please refer http://php.net/manual/en/function.curl-setopt.php, search for 'CURLOPT_POSTFIELDS', again this explanation of using '@' is available. 

Basically, '@' instructs curl to send it as a file rather than a string.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
