### ISSUE TITLE
getInsights always returns null

### ISSUE THREAD

**Issue by ticholNyler** [facebook/facebook-php-business-sdk#297]
I am trying to get CPC for each campaign in a loop and I get all the information but the cpc is alway returning null for each campaign. Here is my code.

```
$api = Api::instance();

$id = trim($_POST['actid']);

$account = new AdAccount($id);

$fields = array(
  	CampaignFields::NAME,
  	CampaignFields::ID,
);

$campaigns = $account->getCampaigns($fields);
	


$cleanArray = [];
foreach ($campaigns as $campaign) {
	
	$campFields = array(
		AdsInsightsFields::CPC,
	);
	
	$campObj = new Campaign($campaign->{CampaignFields::ID});
	
	$params = array(
  		'time_range' => array(
    	'since' => (new DateTime("-1 day"))->format('Y-m-d'),
    	'until' => (new DateTime('NOW'))->format('Y-m-d'),
  		),
  	);
	
	$campInsights = $campObj->getInsights($campFields, $params);
    $innerArray = [];
    array_push($innerArray,$campaign->{CampaignFields::NAME});
    array_push($innerArray,$campaign->{CampaignFields::ID});
	array_push($innerArray,$campInsights->{AdsInsightsFields::CPC});
    array_push($cleanArray,$innerArray);
}
	
header('Content-Type: application/json');
echo json_encode($cleanArray);`
```

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues!

May I get more information regarding this? Are you able to get the CPC info from Facebook UI (Ads Manager)? If the info is not available through Ads Manager either, it's another issue. If you can actually get the info from Ads Manager, could you share your account id (id only; no token) so we can take a deeper look? Thanks!

**Comment by tniggle** [comment]
Sorry just saw this. Yes I can see cost per result in ads manager at campaign level for cost per click. The ad account is 10206475259431108. Thanks

**Comment by tniggle** [comment]
So I am able to see the object returned with the protected data but what is the method to echo the cpc field. Documentation really needs to be extended for this.

**Comment by fjbotto** [comment]
Hey @tniggle i'm trying to use your example, but i get an error. "Class 'AdAccount' not found"
Any help would be awesome!

My code:
`require_once __DIR__ . '/vendor/autoload.php';
use FacebookAds\Api;
$id = 'XXXXXXXXX';
$account = new AdAccount($id);

$fields = array(
  	CampaignFields::NAME,
  	CampaignFields::ID,
);

$campaigns = $account->getCampaigns($fields);
print_r($campaigns);`

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
