### ISSUE TITLE
Adset Returning 

### ISSUE THREAD

**Issue by tojonol** [facebook/facebook-php-business-sdk#299]
When creating the array to send to create AdSet I'm having no issues with most parameters:: 
```
$adSet = new FacebookAds\Object\AdSet(null, 'act_' . $this->adAccountId);
 $adSet->setData(array(
AdSetFields::NAME => ...
...AdSetFields::STATUS => ...
  ));
```

But when I add the following parameter with my own company instagram ID, or an id from a client:
  `AdSetFields::INSTAGRAM_ACTOR_ID => "{VALID ID}",`

and I'm getting the following response:

{"error":{"message":"(#100) No write permission for ad_asset_feed_api access","type":"OAuthException","code":100,"fbtrace_id":"..."}}

I am able to toggle the Instagram toggle for the AdSet within power editor, I am not sure why it would not be working by API.

**Comment by daphyFB** [comment]
Thanks for reporting ADS API SDK issues!

This doesn't look like a general SDK issue. May I get more information regarding this?

1. Were you be able to actually create an ads with instagram actor in power editor? (You mentioned you can toggle it, but it's different than actually creating an ads.)

2. Could you share the fbtrace_id so we can take a deeper look?

Thanks a lot!

**Comment by tojonol** [comment]
"fbtrace_id":"FRaa0rxt8Wf"

**Comment by daphyFB** [comment]
Hi, from the fbtrace id, this error is from data type error instead of permission error. I'm still wondering if you get the same error while doing it via Facebook UI (Ads Manager or Power Editor)? The error now says "This type of Page post can't be promoted in an ad. Please choose a different Page post to continue."

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
