### ISSUE TITLE
CustomAudience::addUsers() not working

### ISSUE THREAD

**Issue by vikramsingh86** [facebook/facebook-php-business-sdk#306]
I am using this sdk to add custom audience list but it start giving below error:
Fatal error: Call to undefined method FacebookAds\Object\CustomAudience::addUsers() 

Please help me to resolve this issue.

**Comment by Sharatheywa** [comment]
Facing Same Issue, Any help?

**Comment by Sharatheywa** [comment]
Use like this:

$emails = array(
  'test1@example.com',
  'test2@example.com',
  'test3@example.com',
);
$customAudience->createUser([], [
  'payload' => [
    'schema' => CustomAudienceTypes::EMAIL,
    'data' => array_map(function($email) {
      return hash(HashNormalizer::HASH_TYPE_SHA256, $email);
    }, $emails),
  ]
])

working fo me.

**Comment by a-kinder** [comment]
I"m having an issue for this as well, I see that addUsers was added in the last commit but the builds have been failing and addUsers() is not present in my vendor code

**Comment by kvnvandenbrande** [comment]
```
$audienceid = "";
$audience = new CustomAudience($audienceid);
$users = array(
	array('email1@hotmail.com'),
    array('email2@hotmail.com'),
    array('email3@icloud.com'),
    array('email4@hotmail.com')
);
$schema = array(
    CustomAudienceMultikeySchemaFields::EMAIL,
);
$audience = new CustomAudienceMultiKey($audienceid);
$audience->addUsers($users, $schema);
```

Works for me. Hope it will help you

**Comment by ryancwalsh** [comment]
Paul Bain of Facebook said that the SDK accidentally temporarily removed `addUsers`. (https://stackoverflow.com/questions/43822538/how-to-use-createuser-in-facebook-ads-to-replace-deprecated-addusers#comment77362924_44020153).  Try updating your local copy of the SDK to 2.9.2 or higher.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
