### ISSUE TITLE
$account = new AdAccount($account_id); doesn't work

### ISSUE THREAD

**Issue by lithewall** [facebook/facebook-php-business-sdk#307]
I'm trying to get account info from marketing API.
First I config app_id, app_secret, account_id.
After that I get the access token from Fb graph API with permission: ads_read,ads_management,business_management

  
Finally I call:

$account = new AdAccount($account_id);
print ("Here 1");
$account->read();
print ("Here 2");

The result just print "Here 1", the program is die before the line print ("Here 2");

I don't know what wrong with my code, could some one please help me? Thank you very much!

**Comment by fjbotto** [comment]
@lithewall hey im sorry, it's been a long since you wrote this, but im stuck with this, where you able to get Ads info? Any help would be appreciate!

Ty

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
