### ISSUE TITLE
ReachEstimate return is not the same as document

### ISSUE THREAD

**Issue by AnonymousArthur** [facebook/facebook-php-business-sdk#308]
In document reach estimate end point suppose to return "bid_estimations", I can get this field through v2.8 api but not v2.9. What's happening here?
This can be easily tested in postman:
`ACCOUNT_ID/reachestimate?targeting_spec={"age_max":14,"age_min":13,"geo_locations":{"location_types":["home","recent"],"countries":["IN","US","HK"]},"publisher_platforms":["facebook","instagram","audience_network","messenger"],"facebook_positions":["feed","right_hand_column","instant_article"],"instagram_positions":["stream"],"device_platforms":["mobile","desktop"],"messenger_positions":["messenger_home"],"genders":[2]}`

**Comment by asim-masood** [comment]
Removed bid_estimations field from /reach_estimates endpoint and moved all of the documented functionality over to /delivery_estimate

/adgroup_id/reach_estimate has been deprecated since it provides no different information than /account_id/reach_estimate

See change log: https://developers.facebook.com/docs/apps/changelog/

**Comment by ultraN** [comment]
@asim-masood 
Thanks for reply. I acknowledged this change, but all estimation I can get from the [ACCOUNT_ID]/delivery_estimate is 0, other fields are fine.

**Comment by asim-masood** [comment]
{
  "error": {
    "message": "(#100) For field 'delivery_estimate': The parameter optimization_goal is required",
    "type": "OAuthException",
    "code": 100,
  }
}

try with optimization_goal

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
