### ISSUE TITLE
'Invalid parameter' when creating ad in facebook using php

### ISSUE THREAD

**Issue by ManojPabani** [facebook/facebook-php-business-sdk#311]
$targeting = new Targeting();
$targeting->{TargetingFields::GEO_LOCATIONS} =
  array(
    'countries' => array('US')
  );
$start_time = (new \DateTime("+1 week"))->format(DateTime::ISO8601);
$end_time = (new \DateTime("+2 week"))->format(DateTime::ISO8601);
$adset = new AdSet(null, 'act_576834712392868');
$adset->setData(array(
  AdSetFields::NAME => 'My Suite CRM Ad Set',
  AdSetFields::OPTIMIZATION_GOAL => AdSetOptimizationGoalValues::REACH,
  AdSetFields::BILLING_EVENT => AdSetBillingEventValues::IMPRESSIONS,
 AdSetFields::BID_AMOUNT => 2,
 AdSetFields::DAILY_BUDGET => 4000,
  AdSetFields::CAMPAIGN_ID => 6069763436431,
  AdSetFields::TARGETING => $targeting,
  AdSetFields::START_TIME => $start_time,
  AdSetFields::END_TIME => $end_time,
));
$adset->create(array(
  AdSet::STATUS_PARAM_NAME => AdSet::STATUS_PAUSED,
));

error is:
Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'Invalid parameter' 

I guess this is due to BILLING_EVENT parameter but on removing this parameter i get another error of missing parameter.

**Comment by bartclaeys** [comment]
Add this to the `Exception` of `new Ad()` for more details:

```
 echo 'Error User Title: ' .$e->getErrorUserTitle() ."<br/>";
 echo 'Error User Message: ' .$e->getErrorUserMessage() ."<br/>";
```

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
