### ISSUE TITLE
Calls to this api have exceeded the rate limit

### ISSUE THREAD

**Issue by bartclaeys** [facebook/facebook-php-business-sdk#312]
In `adgroup_creation.php` I simply replace the setup details (app ID, app secret, account ID & access token) and after running it twice I get the error: `Calls to this api have exceeded the rate limit`

What am I doing wrong?

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
