### ISSUE TITLE
get headers from response

### ISSUE THREAD

**Issue by Smolevich** [facebook/facebook-php-business-sdk#313]
In class /src/FacebookAds/Http/Adapter/CurlAdapter.php method parseHeaders
If in headers have a following line
`
x-fb-ads-insights-throttle: {"app_id_util_pct": 0.00,"acc_id_util_pct": 0.00}
`  then in line 128 code is incorrect parsing header line 
`
list ($key, $value) = explode(': ', $line);
`
In result $value equal  
`
{"app_id_util_pct" 
`

**Comment by Smolevich** [comment]
https://github.com/facebook/facebook-php-ads-sdk/pull/316

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
