### ISSUE TITLE
AbstractCrudObject::getManyByConnection and AbstractCrudObject::getOneByConnection throw parent_id warning 

### ISSUE THREAD

**Issue by arlaneenalra** [facebook/facebook-php-business-sdk#315]
We're seeing this: `$parent_id as a parameter of constructor is being deprecated, please try not to use this in new code.` in the output for a cron job. I've scoured our code and can't find anywhere that we are currently using `new <object>($id, $parent_id)` style instantiation.

Digging deeper, I'm seeing:
https://github.com/facebook/facebook-php-ads-sdk/blob/613d89fbe0424d017a5156658b4e324fbfb5be68/src/FacebookAds/Object/AbstractCrudObject.php#L357-L358

and:

https://github.com/facebook/facebook-php-ads-sdk/blob/613d89fbe0424d017a5156658b4e324fbfb5be68/src/FacebookAds/Object/AbstractCrudObject.php#L381

Which appear to be uses of the deprecated feature. Any idea when this will be fixed? Or suggestions on how to avoid this spamming our logs?

**Comment by arlaneenalra** [comment]
In addition ... I *think* https://github.com/facebook/facebook-php-ads-sdk/blob/d51193b19d730ae9274d45540986e1ac311b074d/src/FacebookAds/Object/AdVideo.php#L84-L88 is the method that is actually causing us issues ...

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
