### ISSUE TITLE
Creative spec must be an associative array (optionally json-encoded) 

### ISSUE THREAD

**Issue by bartclaeys** [facebook/facebook-php-business-sdk#318]
Using the sample code found at:

[https://github.com/facebook/facebook-php-ads-sdk/blob/master/examples/adgroup_creation.php](https://github.com/facebook/facebook-php-ads-sdk/blob/master/examples/adgroup_creation.php)

I'm running into an issue with the last step, `new Ad()`. The error I'm getting back is:

`Creative spec must be an associative array (optionally json-encoded) `

Anybody knows what they mean with `creative spec`?

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
