### ISSUE TITLE
$adCreative->read() without specifying fields

### ISSUE THREAD

**Issue by victorarthur** [facebook/facebook-php-business-sdk#320]
Ideally, I would like to change the url_tags on a cloned AdCrative but as it's not supported by the API as far as I know...

```php
    $ad_creative->setData([
        AdCreativeFields::NAME     => 'Ad2',
        AdCreativeFields::URL_TAGS => 'utm_medium=Ad2';
    ]);

    $ad_creative->update();
```

I need to "download" all data associated with the given AdCreative and re-create it with the new url_tags.

What would be the best way to read all fields and relations associated with the AdCreative? (We don't know in advance which field has been populated, so all fields and related objects needed, but if I simply list them I get a #100  error code.)

```php
    $fields = $ad_creative->getFields();
    $ad_creative->read($fields);
```

Thanks for your help

**Comment by silvios** [comment]
I am not sure what the best way to go about this.

I was thinking of using reflection to get all the properties from the AdCreativeFields

$reflection = new ReflectionClass(AdCreativeFields::class);
$fields = $reflection->getConstants();


Have you figured this out?

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
