### ISSUE TITLE
getTargetingSearch only returns 'interests'

### ISSUE THREAD

**Issue by bigguy1990** [facebook/facebook-php-business-sdk#323]
From what i can see the function getTargetingSearch should be returning types other than interests but from my numerous different searches that is all i can get the endpoint to return. 
https://developers.facebook.com/docs/marketing-api/targeting-search/v2.9#search

Here is my current code i am not specifying the limit_type parameter so according to the documentation it should default to all types. 

```
$query = array(
    'q' => 'harvard'
);

$adaccount = (new AdAccount('act_XXXXXX'))->getTargetingSearch(array('id','name','type','audience_size','description','path'), $query);
```

If anyone has any hints as to the cause that would be great, Thanks.

**Comment by bigguy1990** [comment]
Awaiting a reply from Facebook as it appears to be a bug in the api endpoint.

**Comment by saidrajafallah** [comment]
plz how to add LimitType
i want add country and region +zip 

  $query = array(
    'q' => 'test',
    'limit'=>'3',
    'LimitType'=>array('age_max'=>13,'country'=>'BE'),
);
............

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
