### ISSUE TITLE
flexible_spec BUGS

### ISSUE THREAD

**Issue by zengyi584920** [facebook/facebook-php-business-sdk#326]
$flexible_spec[] = ["interests"=>$adinterests];
        $flexible_spec[] = ["interests"=>[["id"=>"6003346592981","name"=>"线上购物"]]];
         $tagerDatas[TargetingFields::FLEXIBLE_SPEC] = $flexible_spec;
OR
        
        $flexible_spec[] = ["interests"=>[["id"=>"6003346592981","name"=>"线上购物"]]];
       $flexible_spec[] = ["interests"=>$adinterests];
       $tagerDatas[TargetingFields::FLEXIBLE_SPEC] = $flexible_spec;

Both of the results are same. see the below
-------------------------------------------------------
            [flexible_spec] => Array
                (
                    [0] => Array
                        (
                            [interests] => Array
                                (
                                    [0] => Array
                                        (
                                            [id] => 6003346592981
                                            [name] => 线上购物
                                        )

                                )

                        )

                    [1] => Array
                        (
                            [interests] => Array
                                (
                                    [0] => Array
                                        (
                                            [id] => 6003146718552
                                            [name] => 赛车
                                        )

                                    [1] => Array
                                        (
                                            [id] => 6003331671094
                                            [name] => 奥迪Q7
                                        )

                                    [2] => Array
                                        (
                                            [id] => 6003346592981
                                            [name] => 线上购物
                                        )

                                )

                        )

                )
--------------------------------------
Who can help me?thanks.

**Comment by guxufb** [comment]
Could you clarify your question?  It looks like the results are expected based on your code.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
