### ISSUE TITLE
CustomAudience::removeUsers() not working

### ISSUE THREAD

**Issue by kvnvandenbrande** [facebook/facebook-php-business-sdk#330]
For adding users I use the following code:
```
$audienceid = "";
$audience = new CustomAudience($audienceid);
$users = array(
	array('email1@hotmail.com'),
    array('email2@hotmail.com'),
    array('email3@icloud.com'),
    array('email4@hotmail.com')
);
$schema = array(
    CustomAudienceMultikeySchemaFields::EMAIL,
);
$audience = new CustomAudienceMultiKey($audienceid);
$audience->addUsers($users, $schema);
```
Whenever I check in the audiences overview in Facebook and click on the detail of the audience it gives me: Custom audience updated - added x amount of row

For deleting I use the same line of code except changing addUser to removeUsers
```
$audienceid = "";
$audience = new CustomAudience($audienceid);
$users = array(
	array('email1@hotmail.com'),
    array('email2@hotmail.com'),
    array('email3@icloud.com'),
    array('email4@hotmail.com')
);
$schema = array(
    CustomAudienceMultikeySchemaFields::EMAIL,
);
$audience = new CustomAudienceMultiKey($audienceid);
$audience->removeUsers($users, $schema);
```
When checking the audience detail again it now shows Custom audience updated - removed x amount of row. However the size of the audience does not decrease? Is this an SDK issue of Facebook?

**Comment by moometric** [comment]
Same issue, but using External ID to delete users. Can see rows are deleted, but the audience size isn't reducing.

**Comment by kvnvandenbrande** [comment]
I have contacted Facebook support about this issue and it is currently being processed. At this moment I am waiting an reply of the tech support where they have forwarded this issue. 

If you manually upload an CSV and select 'adding customers' it shows: added x amount of row. If you then manually upload the same CSV and select 'remove customer' it shows: removed x amount of rows. The size of the audience does however not decrease. So its not an SDK issue. 

If Facebook contacts me back, I will update this ticket! 
As for now I am waiting and hoping I will soon be able to publish my application that's written for an customer..

**Comment by moometric** [comment]
@kvnvandenbrande - didn't even think to test like that. Good to know. In general it is a bit suck that it takes up to 24 hours to 'remove' and update the audience. makes testing harder.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
