### ISSUE TITLE
Image Retrain Inception only check the own specific category not tensor dataset

### ISSUE THREAD

**Issue by ManojPabani** [facebook/facebook-php-business-sdk#332]
I have retrained the inception model from my data set of traffic sign.Its working fine but when I am trying to check other image e.g panda it's resulting with the name of traffic sign with some probabilities.I don't understand why its doing it.I need both tensor-flow data-set and my own category too. My steps:

-I have installed the python 3.5.2 in windows 7

-I installed tensor-flow with  pip --install tensorflow

-I download these two files retrain.py to train my data and label_image.py to check image.

files downloaded from: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/image_retraining

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
