### ISSUE TITLE
Infinite loop getting AsyncJob Insights results with cursor object

### ISSUE THREAD

**Issue by davidcv91** [facebook/facebook-php-business-sdk#333]
Hi, I think that I've found a bug on last version of Facebook PHP Ads SDK.

This is a piece of my code:
```
$fields = array('ad_id');
$params = array(
    'level' => 'ad',
    'date_preset' => 'yesterday',
    'filtering' => "[{'field':'impressions','operator':'GREATER_THAN','value':'0'}]",
);

$adIds = array();

while (!$asyncJob->read()->isComplete()) {
    echo "SLEEPING...\n";
    sleep($interval);
}

$cursor = $asyncJob->getInsights();

while ($cursor->getNext()) {
    $cursor->fetchAfter();

    //INFINITE LOOP! <<<<<<<<<<<<<<<<<<<<<
}

while ($cursor->valid()) {
    $adInsightsData = $cursor->current()->getData();

    $adIds[] = $adInsightsData['ad_id'];

    $cursor->next();
}

```

I'm looping on a cursor returned by async job to get all insights, but when there are no results `$cursor->getNext()` always returns a URL with the next page and this cause the error `(#17) User request limit reached` due to amount of calls to API.

I've printed the value of `$cursor->getNext()` on each iteration and this is the result when last page is reached:

> [...]
> https://graph.facebook.com/v2.9/198007684064155/insights?access_token=<MY_ACCESS_TOKEN>&limit=25&after=MTk5  
> 
> https://graph.facebook.com/v2.9/198007684064155/insights?access_token=<MY_ACCESS_TOKEN>&limit=25&after=MjI0   (this is the last page)
> 
> https://graph.facebook.com/v2.9/198007684064155/insights?access_token=
><MY_ACCESS_TOKEN>&limit=25&after=MjQ2
> 
> https://graph.facebook.com/v2.9/198007684064155/insights?access_token=<MY_ACCESS_TOKEN>&limit=25&after=MjQ2
> [...]

Looking at `Cursor` class code, I've found that `getNext()` method gets the next page URL based on `$content['paging']['next']` value, but when it's missing (reached last page of results) it generates the URL with `$content['paging']['cursors']['after']` which seems to contains always a value even if there are no more results.

I've posted this bug on Facebook Developers (https://developers.facebook.com/bugs/832337773583415/) but they redirected me to Github. 

![1](https://user-images.githubusercontent.com/11268978/27868404-e55d6700-619c-11e7-88d9-4505b37b8df9.png)
![2](https://user-images.githubusercontent.com/11268978/27868405-e55f7022-619c-11e7-98c9-dee19d34862e.png)
![3](https://user-images.githubusercontent.com/11268978/27868406-e561ee24-619c-11e7-9cdd-128b63bb6212.png)

**Comment by davidcv91** [comment]
Hi, do you have an update for this issue? 
What should I do if I want to get cursor results without using implicit fetching?

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
