### ISSUE TITLE
php get audience 

### ISSUE THREAD

**Issue by saidrajafallah** [facebook/facebook-php-business-sdk#334]
you need simple script php passing parm =>interests, locations (cities, countries, even zip codes) get result For now I use UI of facebook to see the audience I will like a small script in php, I will pass it to parramit as ui When I execute the script return the same result as UI

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
