### ISSUE TITLE
*** is not valid for breakdowns param

### ISSUE THREAD

**Issue by myzingy** [facebook/facebook-php-business-sdk#336]
use ads sdk;
...init...
$ad=new Ad('60848*****2764');
$res=$ad->getInsights($fields,array(
     'breakdowns'=>'creative_fingerprint'
));

ERROR:
(#100) creative_fingerprint is not valid for breakdowns param. please check https://developers.facebook.com/docs/marketing-api/insights/breakdowns/ for all valid values

I've tried all breakdowns parameters，Errors can also occur with these parameters 

> creative_fingerprint,household_composition,household_income,platform_position

help me , i hope "creative_fingerprint" can run

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
