### ISSUE TITLE
About AdUser

### ISSUE THREAD

**Issue by fattalgazi** [facebook/facebook-php-business-sdk#350]
After upgrading my SDK from 2.8.1 to 2.8.2 AdUser class is gone.

```
Exception: Class 'FacebookAds\Object\AdUser' not found
```

But when I look your tests folder, you are still using AdUser object, 

<img width="995" alt="screen shot 2017-08-14 at 10 16 54" src="https://user-images.githubusercontent.com/3602109/29261770-f4347366-80d9-11e7-98a0-19aa6956d4ec.png">

When I look your [v2.8.2](https://github.com/facebook/facebook-php-ads-sdk/releases/tag/2.8.2) release , I can not see any comment about it too!

Congrats for enlighting us! 

Now my project is not working anymore and I don't know which class I should use!

**Comment by fattalgazi** [comment]
People who getting this error, use AdAccountUser

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
