### ISSUE TITLE
AdCampaign Missing

### ISSUE THREAD

**Issue by fjbotto** [facebook/facebook-php-business-sdk#356]
Hi, i already search all over, and AdCampaign file is missing (FacebookAds\Object\AdCampaign). In this github is missing too.

But in your usage examples you use it as a Campaign getter info.

I already installed/tested composer, and its fine.

More info about issue: [https://stackoverflow.com/questions/45805227/facebook-adcampaign-missing](url)

Any help?

**Comment by gutibs** [comment]
Same problem here, anyone has the answer?

**Comment by pbappia** [comment]
The AdCampaign class was renamed in 225ed62295a203c3ce30b7be3f6eb890eced3f90 to Campaign in order to be consistent with the endpoints.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
