### ISSUE TITLE
Readme - DAILY_SPEND_LIMIT - Undefined class

### ISSUE THREAD

**Issue by fjbotto** [facebook/facebook-php-business-sdk#357]
Following the readme file in this example:

`use FacebookAds\Object\AdAccount;
use FacebookAds\Object\Fields\AdAccountFields;

$fields = array(
  AdAccountFields::ID,
  AdAccountFields::NAME,
  AdAccountFields::DAILY_SPEND_LIMIT,
);
$account_id = "XXXXX";
$account = new AdAccount($account_id);
$account->read($fields);`

I'm getting this error: Fatal error: Undefined class constant 'DAILY_SPEND_LIMIT'

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
