### ISSUE TITLE
ad actions action_reaction:anger

### ISSUE THREAD

**Issue by liangjiali** [facebook/facebook-php-business-sdk#358]
How do I use php-ads-sdk to obtain action_reaction "anger" value in MarketApi v2.10? Who can provide the correct code, please? thinks!

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
