### ISSUE TITLE
Whenever tried to create AdImage it gives the following error

### ISSUE THREAD

**Issue by nkmswot** [facebook/facebook-php-business-sdk#359]
ErrorException in AdImage.php line 208:
finfo_file(): Failed identify data 0:(null)

**Comment by blackOfCode** [comment]
Is there any solution to this problem upstairs? Because I have the same problem and worry about it

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
