### ISSUE TITLE
RequestException when code = 190 and subcode = 490

### ISSUE THREAD

**Issue by clin407** [facebook/facebook-php-business-sdk#367]
When accessing the API, sometimes it'll return a requestexception when the code = 190 and the subcode is 490. I did a dump of the response and it's this: 

Error: ```Type error: Argument 1 passed to FacebookAds\Http\Exception\RequestException::idx() must be of the type array, string given, called in /site.com/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php on line 126```

dump
```"message" => "Error validating access token: The user is enrolled in a blocking, logged-in checkpoint"
"type" => "OAuthException"
"code" => 190
"error_subcode" => 490
"error_data" => "
{"checkpoint_flow_id":"207799259245384","checkpoint_content_id":"0"}
"
"fbtrace_id" => "xx"
```

Looks like the issue is when it tries to pass thru error_data since it's a string and not an array.

**Comment by nik1004** [comment]
same issuie

**Comment by felixlehmann** [comment]
same here. v2.11

**Comment by jingping2015** [comment]
This should be fix in our next version release.
