### ISSUE TITLE
getting 'failed creating formpost data' while calling adImage - facebook api error

### ISSUE THREAD

**Issue by nkmswot** [facebook/facebook-php-business-sdk#369]
getting 'failed creating formpost data' while calling adImage. How can i override this error?

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
