### ISSUE TITLE
Call to undefined method FacebookAds\Object\AdCreative::getPreviews()

### ISSUE THREAD

**Issue by biscolab** [facebook/facebook-php-business-sdk#383]
As suggested by the official documentation at https://developers.facebook.com/docs/marketing-api/generatepreview/v2.9 page I get the following error: **Call to undefined method FacebookAds\Object\AdCreative::getPreviews()**.
I had to replace it with **getAdPreviews** method:
```php
$creative->getAdPreviews(array(), array(AdPreviewFields::AD_FORMAT => AdPreviewAdFormatValues::DESKTOP_FEED_STANDARD,));
```

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
