### ISSUE TITLE
Can we add a getCustomConversions method to AdAccount?

### ISSUE THREAD

**Issue by red-crown** [facebook/facebook-php-business-sdk#388]
It would be nice to be able to fetch an account's custom conversions. We already have the create method so a read would be nice.

**Comment by hakimio** [comment]
@windsfantasy6 Can you be so kind and add missing "getCustomConversions()" method to AdAccount class. I am sure copy-pasting some code wouldn't take much time at all.

**Comment by hakimio** [comment]
@duliomatos

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.

**Comment by hakimio** [comment]
@jingping2015 The issue is still present in the latest version. Reopen.
