### ISSUE TITLE
Ad Image deletion

### ISSUE THREAD

**Issue by WaskiWabit** [facebook/facebook-php-business-sdk#389]
When deleting an ad image, the class AdImage.php has a method called "delete" that calls parent::delete($params), but there is no delete method on the parent AbstractCrudObject.

https://github.com/facebook/facebook-php-ads-sdk/commit/d51193b19d730ae9274d45540986e1ac311b074d#diff-dc21651d18a000b1c609c85d16d1bcf7

**Comment by quanton81** [comment]
Had the same problem
The facebook tutorial says:
`$image = new AdImage(<IMAGE_ID>, 'act_<AD_ACCOUNT_ID>');`
`$image->{AdImageFields::HASH} = '<IMAGE_HASH>';`
`$image->deleteSelf();`
but it doesn't work

to delete an image you have to do:
`$image = new AdImage(<IMAGE_ID>, 'act_<AD_ACCOUNT_ID>');`
`$image->{AdImageFields::HASH} = '<IMAGE_HASH>';`
`$image->deleteSelf(['hash' => $image->{AdImageFields::HASH}]);`
Hope facebook will resolve the issue or update the guide.

A solution is to change the delete function to:

`public function delete(array $params = array()) {
    if (!$this->data[AdImageFields::HASH]) {
        throw new \Exception("AdImage hash is required to delete");
    }
    $params = array_merge($params, array('hash' => $this->data[AdImageFields::HASH]));
    parent::deleteself($params);
}`
the only part to change is:
`parent::deleteself($params);`
 from
`parent::delete($params);`

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
