### ISSUE TITLE
[How to know new download in fb sdk]

### ISSUE THREAD

**Issue by minhliem86** [facebook/facebook-php-business-sdk#390]
Dear all,

I'm beginner in facebook php ads sdk. I develop the download new Leads function. I can get link download by leadgen_form method. But now I need download the new leads only (that not include leads which I downloaded before), something like facebook download  feature. So how can I do that ?
(Sorry all about my English).

Thanks for your supporting.

**Comment by lintaocui** [comment]
Can you elaborate more about your questions?

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
