### ISSUE TITLE
Class AdAccountPermittedRolesValues missed!

### ISSUE THREAD

**Issue by zoonman** [facebook/facebook-php-business-sdk#393]
Here is the enum class https://github.com/facebook/facebook-php-ads-sdk/blob/2.10.1/src/FacebookAds/Object/Values/AdAccountPermittedRolesValues.php

The referenced documentation

https://developers.facebook.com/docs/marketing-api/reference/ad-account/assigned_users/
https://developers.facebook.com/docs/marketing-api/businessmanager/assets

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.

**Comment by zoonman** [comment]
I checked. The `AdAccountPermittedRolesValues` class is present under `FacebookAds\Object\Values` namespace. Everything is fine. Thank you!
