### ISSUE TITLE
new \new FacebookAds\Object\User('me') throws an error in 2.11

### ISSUE THREAD

**Issue by Eldair** [facebook/facebook-php-business-sdk#394]
In previous version of the SDK I was able to construct an object of class  FacebookAds\Object\User with 'me' as a parameter (new User('me')) which now (in 2.11) throws an error.

**Comment by ondrejfuhrer** [comment]
I had a similar issue with `AdAccountUser` and I solved it by not passing the id to constructor but using `setId`. So instead of 
```php
$user = new AddAccountUser('me');
```
I have:
```php
$user = new AddAccountUser();
$user->setId('me')
```

Maybe this will help you as well.

**Comment by Eldair** [comment]
👍 works with the User class as well

**Comment by MordiSacks** [comment]
@ondrejfuhrer Thank you.
this issue was bugging me.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
