### ISSUE TITLE
PHP Fatal error:  Uncaught FacebookAds\Http\Exception\AuthorizationException: Syntax error "Expected "(" instead of ","." at character 2220:

### ISSUE THREAD

**Issue by DesRodman** [facebook/facebook-php-business-sdk#397]
Good day...
I used instruction:

> Follow these steps to run the SAMPLE_CODE file you downloaded in the previous section.
> If you haven't yet, you'll need to download the Facebook Marketing SDK in Php. Enter the following git command in your terminal to download it:
> git clone https://github.com/facebook/facebook-php-ads-sdk.git
> Navigate to the root of the facebook- php-ads-sdk by running the following command:
> cd facebook-php-ads-sdk/
> You'll need to install Composer which is a PHP dependecy manager. You can download composer from here. Once composed is installed run the following command to install Facebook PHP Marketing SDK dependencies.
> composer install
> Copy the SAMPLE_CODE. php file that you created in this Quickstart into the current directory. Enter the following command in your terminal:
> cp ~/Downloads/SAMPLE_CODE.php  .
> Now you can run the SAMPLE_CODE.php file by using the following commands:
> php SAMPLE_CODE.php
> Congratulations! You have now successfully executed the sample code.

after trying to launch "php SAMPLE_CODE.php" i have
`PHP Fatal error:  Uncaught FacebookAds\Http\Exception\AuthorizationException: Syntax error "Expected "(" instead of ","." at character 2220: results,result_rate,reach,frequency,impressions,delivery,social_reach,social_impressions,total_actions,total_unique_actions,relevance_score:score,relevance_score:positive_feedback,relevance_score:negative_feedback,spend,today_spend,impressions_gross,impressions_auto_refresh,cost_per_result,cpp,cpm,cost_per_total_action,actions:page_engagement,actions:like,actions:mention,actions:tab_view,actions:comment,actions:post_engagement,actions:post_reaction,actions:post,actions:photo_view,actions:rsvp,actions:receive_offer,actions:checkin,cost_per_action_type:page_engagement,cost_per_action_type:like,cost_per_action_type:mention,cost_per_action_type:tab_view,cost_per_action_type:comment,cost_per_action_type:post_engagement,cost_per_action_type:post_reaction,cost_per_action_type:post,cost_per_action_type:photo_view,cost_per_action_type:rsvp,cost_per_action_type:receive_offer,cost_per_action_type:ch in /var/www/facebookapi/facebook-php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php on line 144`

what i did wrong? maybe wrong version of sdk?!
but i think its last.
Help me please. How can i fix it?

Thanks

**Comment by Valera3221488** [comment]
- https://developers.facebook.com/docs/marketing-api/sdks/ try this tutorial

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
