### ISSUE TITLE
Getting capability error while creating Ad Creative

### ISSUE THREAD

**Issue by bilaliqbal-te** [facebook/facebook-php-business-sdk#399]
Hey guys,
I am having trouble while creating Ad Creative. Each time when I use to create it I got this error
`(#3) Application does not have the capability to make this API call`.
How should I fix this issue, while I have all approved permissions like (ads_management, business_management, ads_read). 

Please guide me what I am missing in the whole process and why am I getting this error.

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
