### ISSUE TITLE
(#12) Deprecated endpoint as of V2.11 is deprecated for versions v2.11 and higher

### ISSUE THREAD

**Issue by ocinside1** [facebook/facebook-php-business-sdk#400]
The method FacebookAds\Object\ProductCatalog::getEndpoint() returns the string 'product_catalogs' and the response error message from the API is '(#12) Deprecated endpoint as of V2.11 is deprecated for versions v2.11 and higher'.
If I change that method to return null like the same method in parent class (FacebookAds\Object\AbstractCrudObject) everything is OK.

**Comment by ricky-cortopassi** [comment]
We had noticed this same issue, as the new end point is owned_product_catalogs OR client_product_catalogs. Since we use composser to install this, changing was not an option so we had just extended that class and overwrote the get endpoint method which seemed to work fine.. ( FOR NOW. ) but far from ideal.

**Comment by med-ezzairi** [comment]
I have same issue, but when I changed the return to null, instead of create a Catalog it changes my business label (Business Manager Info).

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.

**Comment by rauaha** [comment]
In v2.11 and higher, product_catalogs has been deprecated.  
To access business product catalogs

BUSINESS_ID/owned_product_catalogs - To get a list of product catalogs the business owns
BUSINESS_ID/client_product_catalogs - To get a list of product catalogs belonging to clients of the business
