### ISSUE TITLE
Error on getting effective_object_story_id 

### ISSUE THREAD

**Issue by teeosx** [facebook/facebook-php-business-sdk#403]
Hi, I'm using PHP to develop an API. I want to read Post ID from ads creative.
By Calling something like

   $creative = new AdCreative($array[0]);
          $fields = array(
              AdCreativeFields::EFFECTIVE_OBJECT_STORY_ID,
            );    
            $creative->read($fields);
            echo $creative->{AdCreativeFields::EFFECTIVE_OBJECT_STORY_ID}.PHP_EOL;

But I got the error like 

"Tried accessing nonexisting field (effective_object_story_id) on node type (Adgroup) in /Applications/MAMP/htdocs/facebook-php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:144"

Anyone can help me to pass this error ? Thank you very much

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
