### ISSUE TITLE
Create an AdCreative requires an parent_id but when pass in parent_id a warning is shown $parent_id constructor argument is deprecated

### ISSUE THREAD

**Issue by AnonymousArthur** [facebook/facebook-php-business-sdk#405]
Basically to create a new AdCreative by doing this:
`
$a = new AdCreative();
$a->create([Blah])
`
will throw an error says parent_id undefined
However if I do this way:
`
$a = new AdCreative(null, $account_id);
$a->create([Blah])
`
will create the creative but throw a warning says $parent_id constructor argument is deprecated.
which is like an unsolvable bug unless I create the AdCreative through AdAccount object.

Any thoughts?

**Comment by gnumoksha** [comment]
Use `setParentId` method. Like in:

```php
$creative = new AdCreative();
$creative->setParentId($account->id);
```

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
