### ISSUE TITLE
PHP Fatal error:  Uncaught FacebookAds\Http\Exception\AuthorizationException: (#12) Deprecated endpoint as of V2.11 is deprecated for versions v2.11 and higher in vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:140

### ISSUE THREAD

**Issue by leticiasales** [facebook/facebook-php-business-sdk#407]
Here's my Code: ![image](https://user-images.githubusercontent.com/19367966/35154277-c5f80bf8-fd10-11e7-9073-901bb564bf6e.png)
Here's the Error:

➜  * git:(Facebook-Api) ✗ php shell/facebookSetup.php
$parent_id as a parameter of constructor is being deprecated, please try not to use this in new code.

PHP Fatal error:  Uncaught FacebookAds\Http\Exception\AuthorizationException: (#12) Deprecated endpoint as of V2.11 is deprecated for versions v2.11 and higher in /home/tish/workspace/*/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:140
Stack trace:
#0 /home/tish/workspace/*/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(215): FacebookAds\Http\Exception\RequestException::create(Object(FacebookAds\Http\Response))
#1 /home/tish/workspace/*/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request))
#2 /home/tish/workspace/*/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(151): FacebookAds\Http\Request->execute()
#3 /home/tish/workspace/*/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(193): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request))
#4 /home/tish/workspace/*/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php(219): Face in /home/tish/workspace/*/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php on line 140

**Comment by spi-ke** [comment]
It should use new endpoints changed in v2.11 Graph API
https://developers.facebook.com/docs/graph-api/changelog/version2.11#mapi-new-BM

**Comment by gnumoksha** [comment]
Duplicated with https://github.com/facebook/facebook-php-ads-sdk/issues/400

**Comment by ellentao** [comment]
Thanks for helping on this issue!
