### ISSUE TITLE
Missing "MESSAGES" in CampaignObjectiveValues enum

### ISSUE THREAD

**Issue by leafnode** [facebook/facebook-php-business-sdk#408]
I was trying to use "MESSAGES" campaign objective via the SDK, but it appeared that this value does not exist in the CampaignObjectiveValues enum. This option was introduced quite some time ago, and it's described in the [API documentation](https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group). From what I've checked, it's the only value missing from the enum.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
