### ISSUE TITLE
Lost data of ENUM on AdCreativeLinkDataCallToActionTypeValues.php

### ISSUE THREAD

**Issue by tiger154** [facebook/facebook-php-business-sdk#409]
Hi I was testing to create an ad with this SDK. 

And I found a bug which don't support matched ENUM values from AdCreativeLinkDataCallToActionTypeValues.php

From the link there are 'type' field with ENUM datas
 -  https://developers.facebook.com/docs/marketing-api/reference/ad-creative-link-data-call-to-action/ 

And it's not matched with this SDK version 2.11.*

For example I was looking for 'EVENT_RSVP' value in the object. But there wasn't the data.

So can you please me point out if you need to update or I was looking at wrong Object?

Thank you~

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
