### ISSUE TITLE
Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message with message 'Unsupported get request.

### ISSUE THREAD

**Issue by carolinepk** [facebook/facebook-php-business-sdk#414]
Everything was working perfectly until the end of last year, then we've had a token expired.
Token has been reset with absolutely no change and we get this error in return.
If token get

All that we are trying to do is this : cf. below
What is surprising is that the day after, the error is that the token is expired. So we regenerate a test token and then we get this error again. Please help it makes no sense
use FacebookAds\Object\AdAccount;
use FacebookAds\Object\Fields\AdAccountFields;

$account = new AdAccount('act_<AD_ACCOUNT_ID>');
$account->read(array(
  AdAccountFields::TOS_ACCEPTED,
));

// Dump TOS Accepted info.
var_dump($account->{AdAccountFields::TOS_ACCEPTED});

**Comment by timothymarois** [comment]
I am also seeing this. I like to point out that this API should not be providing any HTTP Status (header) changes. 

`Object(FacebookAds\Http\Exception\AuthorizationException)`

My framework exception comes in with the following message:

`Unknown HTTP status code provided with no message`

**Comment by gnumoksha** [comment]
The `RequestException` and  `AuthorizationException` has useful methods for figure out what is happening, like: `getErrorUserTitle`, `getErrorUserMessage` and `getHttpStatusCode`.

**Comment by ellentao** [comment]
Hi,

Thanks for your comments! Recently we have updated the SDK to v3.0 version. If you still see this issue, please provide the error message as @gnumoksha mentioned. Thank you!
