### ISSUE TITLE
marketing api failed: PHP Fatal error

### ISSUE THREAD

**Issue by bmbraga** [facebook/facebook-php-business-sdk#415]
I am running this code:
`/**
 * libs
 */
require_once DOCUMENT_ROOT.'_libs/facebook-ads-sdk/autoload.php';

/**
 * class
 */
use FacebookAds\Object\AdAccount;
use FacebookAds\Object\AdsInsights;
use FacebookAds\Api;
use FacebookAds\Logger\CurlLogger;

/**
 * vars
 */
$access_token = '';

$ad_account_id = '';
$app_secret = '';
$app_id = '';

/**
 * FaceADS
 */
$api = Api::init($app_id, $app_secret, $access_token);
$api->setLogger(new CurlLogger());

$fields = array(
  'delivery',
  'impressions',
  'cpm',
  'cost_per_action_type:link_click',
  'website_ctr:link_click',
  'spend',
  'mobile_app_purchase_roas:app_custom_event.fb_mobile_purchase',
  'relevance_score:positive_feedback',
  'relevance_score:negative_feedback',
);
$params = array(
  'level' => 'adset',
  'filtering' => array(),
  'breakdowns' => array(),
  'time_range' => array('since' => '2017-12-09','until' => '2018-02-07'),
);

echo json_encode((new AdAccount($ad_account_id))->getInsights(
  $fields,
  $params
)->getResponse()->getContent(), JSON_PRETTY_PRINT);
`
And this error returns:
`PHP Fatal error:  Uncaught FacebookAds\\Exception\\Exception in /home/ebemestar/public_html/_libs/facebook-ads-sdk/FacebookAds/Http/Adapter/CurlAdapter.php:196\nStack trace:\n#0 /home/ebemestar/public_html/_libs/facebook-ads-sdk/FacebookAds/Http/Client.php(204): FacebookAds\\Http\\Adapter\\CurlAdapter->sendRequest(Object(FacebookAds\\Http\\Request))\n#1 /home/ebemestar/public_html/_libs/facebook-ads-sdk/FacebookAds/Http/Request.php(282): FacebookAds\\Http\\Client->sendRequest(Object(FacebookAds\\Http\\Request))\n#2 /home/ebemestar/public_html/_libs/facebook-ads-sdk/FacebookAds/Api.php(162): FacebookAds\\Http\\Request->execute()\n#3 /home/ebemestar/public_html/_libs/facebook-ads-sdk/FacebookAds/Api.php(204): FacebookAds\\Api->executeRequest(Object(FacebookAds\\Http\\Request))\n#4 /home/ebemestar/public_html/_libs/facebook-ads-sdk/FacebookAds/ApiRequest.php(183): FacebookAds\\Api->call('/act_6030436898...', 'GET', Array, Array)\n#5 /home/ebemestar/public_html/_libs/facebook-ads-sdk/FacebookAds/Object/AdAccount.php(1368): FacebookAds\\ApiRequest->execute in /home/ebemestar/public_html/_libs/facebook-ads-sdk/FacebookAds/Http/Adapter/CurlAdapter.php on line 196`

What can it be? I've tested everything.

**Comment by ellentao** [comment]
Hi,

Thanks for your comment! Recently we have updated SDK to v3.0 version. Does this issue still exist?

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
