### ISSUE TITLE
README Incorrect. Need More Documentation. 

### ISSUE THREAD

**Issue by timothymarois** [facebook/facebook-php-business-sdk#419]
This API needs to be seriously documented. There is no known documentation linked on the readme. I had to comb through the source code to figure out how to call specific methods and figure out I needed to include "fields" for anything to actually print out. The readme is already incorrect as `getCamapigns()` will not give you any information about them without including their fields into the argument. 

_When writing the documentation, don't give bad working examples, its called `TL;DR` All written examples are assumed to be working examples._ 

This is on the readme, **will not work.** 
```php

$cursor = $account->getCampaigns();

foreach ($cursor as $campaign) {
  echo $campaign->{CampaignFields::NAME}.PHP_EOL;
}

```

You must add the fields.

```php

$cursor = $account->getCampaigns(['id','name']);

foreach ($cursor as $campaign) {
  echo $campaign->{CampaignFields::NAME}.PHP_EOL;
}

```

**Comment by jingping2015** [comment]
This should be fix in next release. Thanks for reporting this issue.
