### ISSUE TITLE
Problem getting correct Audience Estimate

### ISSUE THREAD

**Issue by paulm17** [facebook/facebook-php-business-sdk#420]
I'm having an issue where the estimated number is different from what I am expecting.

This is probably something very trivial so any help appreciated.

I'm expecting a figure near to 380k, rather than the 45m I'm getting now.  It seems to be disregarding regions and cities completely.

Here's an example for delivery estimate:

	Api::init($this->APP_ID, $this->APP_SECRET, $access_token);

	$adAccount = new AdAccount($account_id']);

	$targeting_spec = new Targeting();
	$targeting_spec->setData(array(
	    TargetingFields::GEO_LOCATIONS => array(
	        'countries' => array('GB'),
	        'regions' => array(array('key' => '4079')),
	        'cities' => array(
	            array(
	                'key' => '816260',
	                'radius' => 10,
	                'distance_unit' => 'mile',
	            ),
	        ),
	    )
	));

	$delivery_estimate = $adAccount->getDeliveryEstimate(
		array(),
		array(
			'currency' => 'USD',
			'optimization_goal' => 'NONE',
			'targeting_spec' => $targeting_spec,
		)
	);

	$mau = $delivery_estimate->current()->estimate_mau;

For reach estimate, I was using:

	$reach_estimate = $adAccount->getReachEstimate(
		array(),
		array(
			'currency' => 'USD',
			'optimize_for' => 'OFFSITE_CONVERSIONS',
			'targeting_spec' => $targeting_spec,
		)
	);

	$users = $reach_estimate->current()->users;

Although returns the same result.  

Also If someone can clarify whether reach estimate has been deprecated or not.

I'm using Ads API 2.11.

**Comment by paulm17** [comment]
Following up.  I have found, that if I omit countries and then regions.  I get closer to the amount that I am looking for.

Does this mean, the lower in level relating to countries, regions, cities, etc.  The specific level I need to submit, otherwise if I have upper levels included, then it will give me results for that level only?

For example.  If I want region.  Then it should be:

	$targeting_spec->setData(array(
	    TargetingFields::GEO_LOCATIONS => array(
	        'regions' => array(array('key' => '4079')),	        ),
	    )
	));

and not

	$targeting_spec->setData(array(
	    TargetingFields::GEO_LOCATIONS => array(
	        'countries' => array('GB'),
	        'regions' => array(array('key' => '4079')),	        ),
	    )
	));

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
