### ISSUE TITLE
get campaign data

### ISSUE THREAD

**Issue by camilo246800** [facebook/facebook-php-business-sdk#421]
Hello, I need to get the amount spent on a campaign, I'm not sure how to do it. I would be grateful if you would indicate that I should use it. Thank you!

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
