### ISSUE TITLE
Update advert: change advert image not effected.

### ISSUE THREAD

**Issue by projects-logiciel** [facebook/facebook-php-business-sdk#430]
I am trying to update imzage and headline of advert. API return success response but link data attributes are not updated.

```
$advertisement = new Ad(23842735796150501);
advertisement->creative = [
       [object_type] => PHOTO
       [object_story_spec] => [
              [link_data] => Array
              [
                      [picture] => http://www.thehindu.com/migration_catalog/article15485191.ece/alternates/FREE_660/08pp%20cover.ART0_GIL21OBG7.1+08pp_Sylvan_County.jpg
              ]         
        ]
]

$advertisement->update();
```

Also tried same from Graph API Explorer

http://graph.facebook.com/2.12/23842735796150501

Request Param

```
['object_story_spec']['link_data']['picture'] = http://www.thehindu.com/migration_catalog/article15485191.ece/alternates/FREE_660/08pp%20cover.ART0_GIL21OBG7.1+08pp_Sylvan_County.jpg
```

Response
```
{
  "success": true
}
```

Graph api explorer Session url - https://developers.facebook.com/tools/explorer/202385023516039/?session_id=820536021463514

According to this ref link https://github.com/facebook/facebook-python-ads-sdk/issues/214Creatives are immutable objects, meaning once created none of their properties can be changed, Is that right ? Is yes the what is that appropriate way to change the image of advert.

**Comment by shootingsyh** [comment]
@projects-logiciel do you mean that you tried to use Graph API Explorer to update the creative but still not updated right?

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
