### ISSUE TITLE
Error while trying get transacions for AdAccount

### ISSUE THREAD

**Issue by dmitryvy** [facebook/facebook-php-business-sdk#433]
Trying to get Transactions for ad account:

 $cursor_transactions = $account->getTransactions($transactionFields, $transactionParams);

and get error:

Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message '(#100) Tried accessing nonexisting field (transactions) on node type (AdAccount)'

It used to work for a year and it seems that they removed this field because I can't find it in FB documentation.

**Comment by wei-fb** [comment]
Hi,

This is the documentation of Ad Account Transactions https://developers.facebook.com/docs/marketing-api/reference/ad-account/transactions/, have you tried using Graph API Explorer to reproduce the error ? https://developers.facebook.com/tools/explorer/145634995501895/?method=GET&path=%7Bad-account-id%7D%2Ftransactions&version=v3.0

**Comment by dmitryvy** [comment]
Hi,

The link you gave to transactions is invalid now and I found out that FB deprecated transactions in API v 3.0. But no information how to get transactions in the new version. COuld it be that they just killed it without any replacement?

**Comment by wei-fb** [comment]
I believe that's the case. It does not have any replacement for it.

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
