### ISSUE TITLE
Read AdAccount read method is not working anymore

### ISSUE THREAD

**Issue by nileshsmartwebtech** [facebook/facebook-php-business-sdk#434]
```
if(is_null($access_token) || is_null($app_id) || is_null($app_secret)) {
  throw new \Exception(
    'You must set your access token, app id and app secret before executing'
  );
}

if (is_null($account_id)) {
  throw new \Exception(
    'You must set your account id before executing');
}

use FacebookAds\Api;
use FacebookAds\Object\AdAccount;
use FacebookAds\Object\Fields\AdAccountFields;

Api::init($app_id, $app_secret, $access_token);


$account = new AdAccount($account_id);
$account->read();
```
getting this error
`Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'A user access token is required to request this resource.' in C:\xampp\htdocs\facebooksdk\facebook-php-ads-sdk\src\FacebookAds\Http\Exception\RequestException.php:144 Stack trace: #0 C:\xampp\htdocs\facebooksdk\facebook-php-ads-sdk\src\FacebookAds\Http\Client.php(215): FacebookAds\Http\Exception\RequestException::create(Object(FacebookAds\Http\Response)) #1 C:\xampp\htdocs\facebooksdk\facebook-php-ads-sdk\src\FacebookAds\Http\Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request)) #2 C:\xampp\htdocs\facebooksdk\facebook-php-ads-sdk\src\FacebookAds\Api.php(162): FacebookAds\Http\Request->execute() #3 C:\xampp\htdocs\facebooksdk\facebook-php-ads-sdk\src\FacebookAds\Api.php(204): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request)) #4 C:\xampp\htdocs\facebooksdk\facebook-php-ads-sdk\src\FacebookAds\Object\AbstractCrudObject.php(268): FacebookAds\Api->call('/13749632037665...', 'GET', in C:\xampp\htdocs\facebooksdk\facebook-php-ads-sdk\src\FacebookAds\Http\Exception\RequestException.php on line 144`

**Comment by wei-fb** [comment]
Hi,

Could you try using Graph API Explorer and see if you can reproduce the error? If you can, you might want to escalate to Facebook support so you can provide access token information to help them look into the issue.

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!

**Comment by nileshsmartwebtech** [comment]
But that guys told me that its sdk issue
