### ISSUE TITLE
facebook-php-ads-sdk\src\FacebookAds\Http\Exception\RequestException.php

### ISSUE THREAD

**Issue by shyamrss** [facebook/facebook-php-business-sdk#435]
facebook ads sdk php create campaign_id but not adset

Fatal error: Uncaught FacebookAds\Http\Exception\AuthorizationException: Invalid parameter in F:\xampp\htdocs\facebook\facebook-php-ads-sdk\src\FacebookAds\Http\Exception\RequestException.php:144 Stack trace: #0 F:\xampp\htdocs\facebook\facebook-php-ads-sdk\src\FacebookAds\Http\Client.php(215): FacebookAds\Http\Exception\RequestException::create(Object(FacebookAds\Http\Response)) #1 F:\xampp\htdocs\facebook\facebook-php-ads-sdk\src\FacebookAds\Http\Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request)) #2 F:\xampp\htdocs\facebook\facebook-php-ads-sdk\src\FacebookAds\Api.php(162): FacebookAds\Http\Request->execute() #3 F:\xampp\htdocs\facebook\facebook-php-ads-sdk\src\FacebookAds\Api.php(204): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request)) #4 F:\xampp\htdocs\facebook\facebook-php-ads-sdk\src\FacebookAds\Object\AbstractCrudObject.php(235): FacebookAds\Api->call('/act_1249843416...', 'POST', Array) #5 F:\xampp\htdocs\facebook\index.php(101): FacebookAds\Object\AbstractCrud in F:\xampp\htdocs\facebook\facebook-php-ads-sdk\src\FacebookAds\Http\Exception\RequestException.php on line 144

please help

**Comment by hellojebus** [comment]
May be an issue related to this bug: https://developers.facebook.com/bugs/707332642990208/

**Comment by wei-fb** [comment]
Hi,

Please take a look at the bug report mentioned above and see if you can still reproduce it. If you still can, please try reproducing errors using Graph API Explorer.

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
