### ISSUE TITLE
Tried accessing nonexisting field (campaigns) on node type (AdAccount)

### ISSUE THREAD

**Issue by hellojebus** [facebook/facebook-php-business-sdk#436]
Getting a #100 failed response code when calling the `getCampaigns` on AdAccount. 

I was not able to see any changes with the new 2.12 API that would cause this break.

Any ideas?

<img width="499" alt="screen shot 2018-04-24 at 1 19 20 pm" src="https://user-images.githubusercontent.com/594042/39211976-22d3b3b2-47c2-11e8-9cc6-bf342c7e9ce7.png">

**Comment by hellojebus** [comment]
It seems others are having the same problem, seems that it could be a bug on FB's end. We keep a close eye out in case we need to include a patch: 

https://developers.facebook.com/bugs/707332642990208/

**Comment by wei-fb** [comment]
The above mentioned bug is resolved. Please see if your issue still persists.
