### ISSUE TITLE
The custom audience rule syntax you are using is too old for Graph API v2.13.

### ISSUE THREAD

**Issue by elygiux** [facebook/facebook-php-business-sdk#437]
I am trying to create a custom audience. Everything worked fine, before I updated to ADS SDK 3.0. Now I am getting this error: "The custom audience rule syntax you are using is too old for Graph API v2.13."

https://developers.facebook.com/docs/marketing-api/reference/custom-audience/v3.0#Creating This does not help.
````
$params = [
            CustomAudienceFields::NAME           => $name . ' Tobi custom audience.',
            CustomAudienceFields::SUBTYPE        => 'WEBSITE',
            CustomAudienceFields::RETENTION_DAYS => 14,
            CustomAudienceFields::RULE           => [
                'and' => [
                    [
                        'event' => ['i_contains' => 'AddToCart'],
                    ],
                    [
                        'event' => ['i_not_contains' => 'Purchase'],
                    ],
                ],

            ],
            CustomAudienceFields::PREFILL        => '1',
            CustomAudienceFields::PIXEL_ID       => $pixelId,
        ];

  try {
            $audience = (new CustomAudience(null, 'act_' . $adAccountId));

            dd($audience->create($params));
        } catch (AuthorizationException $e) {
            Logger::critical($e, 'Failed creating custom audience. User error: ' . $e->getErrorUserMessage());

            dd($e->getErrorUserMessage());

            return (object)[
                'id'    => null,
                'error' => $e->getErrorUserMessage(),
            ];
        }

**Comment by ellentao** [comment]
Hey,

Thanks for your question! This is a break change change for custom audience creation in v3.0. The change log is here: https://developers.facebook.com/docs/graph-api/changelog/version3.0 (search for Audiences and Ads Targeting under "breaking changes"). 

You can still use the old audience rule syntax in previous API versions (<3.0). If you want to use the new version, here are some examples: https://developers.facebook.com/docs/marketing-api/audiences-api/websites#audiencerules.
