### ISSUE TITLE
Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException'

### ISSUE THREAD

**Issue by vivektt** [facebook/facebook-php-business-sdk#439]
I am using this sdk and got issue , 
Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'Unsupported post request. Object with ID '<ACCOUNTID>' does not exist, cannot be loaded due to missing permissions, or does not support this operation at facebook/php-business-sdk/src/FacebookAds/Http/Exception/RequestException.php:163 and FacebookAds\Http\Request->execute(): facebook/php-business-sdk/src/FacebookAds/Http/Exception/RequestException.php on line 163 and facebook/php-business-sdk/src/FacebookAds/Http/Client.php(217): FacebookAds\Http\Exception\RequestException::create(Array, 400)

Please try to resolved it ASAP .

**Comment by shootingsyh** [comment]
@vivektt can you help give more details on your code? Which call are you making and what ID did you provide?

**Comment by shootingsyh** [comment]
Didn't get response. Can you try to see if you provided the correct ad_account id? Did you add the 'act_' prefix to your ad account id when calling the function? 
Will close for now. Please reopen if you have more details
