### ISSUE TITLE
Account insights unavailable

### ISSUE THREAD

**Issue by maxim-novikov** [facebook/facebook-php-business-sdk#441]
Hello,

Whenever I try to access account insights ( get act_XXXXXX/insights ) using 3.0 API, I get the following error message:
`{
  "error": {
    "code": 1,
    "message": "Please reduce the amount of data you're asking for, then retry your request"
  }
}`
It doesn't matter if request comes from app or from the Graph API Explorer. As a workaround I can get the same data on per-campaign basis, but it increases amount of calls significantly. I haven't found anything in the changelog - is that intended behavior?

**Comment by ellentao** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
