### ISSUE TITLE
(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.11

### ISSUE THREAD

**Issue by pgodel** [facebook/facebook-php-business-sdk#442]
Hello,

I just started to get this exception when 2 hours ago these calls were working with no issues, and now I am getting:
 [Facebook\Exceptions\FacebookAuthenticationException (2635)]
  (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.11.

I just checked which PHP package I have installed using composer:
$ composer show -i|grep face
facebook/graph-sdk                     5.6.1              Facebook SDK for PHP
facebook/php-ads-sdk                   2.11.3             PHP SDK for Facebook ads

Can someone provide assistance?
Thanks

**Comment by shootingsyh** [comment]
@pgodel can you try to update to use facebook/php-business-sdk 3.0.0? php-business-sdk is the new version of php-ads-sdk.  It should solve the problem. 
Please note that php-graph-sdk is a different SDK which is for more general GraphAPI calling without builtin object model. 
See https://developers.facebook.com/docs/business-sdk/getting-started for upgrade.
