### ISSUE TITLE
Get Ads from AdSet

### ISSUE THREAD

**Issue by dmanthing** [facebook/facebook-php-business-sdk#449]
Why do we no longer have `const ADS = 'ads';` inside AdSetFields?
Is there any other way to get Ads inside AdSet using AdSetFields?
Thanks

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
