### ISSUE TITLE
Implement changes to custom audiences (new mandatory field, enforced July 2, 2018)

### ISSUE THREAD

**Issue by jspeedz** [facebook/facebook-php-business-sdk#452]
Some changes will be done to the custom audience part of the package. Including the new mandatory field customer_file_source. We would like to implement these before the change is enforced (customer_file_source field added June 13, 2018, will be enforced July 2, 2018).

For more information, see:
https://developers.facebook.com/ads/blog/post/2018/06/13/sharing-custom-audiences/

We cannot add this field ourselves as these classes are auto-generated with codegen. Please add support for this field.

Thank you!

**Comment by vicdus** [comment]
Hi jspeedz,

This field is already available in latest version of SDK. Please update SDK version in `composer.json` which is `3.0.4` in your project

For more versions available, see https://packagist.org/packages/facebook/php-business-sdk

Feel free to reopen this if you still have issue :)
