### ISSUE TITLE
Ad Must Be Associated With a Facebook Page

### ISSUE THREAD

**Issue by palpalani** [facebook/facebook-php-business-sdk#453]
I am trying to create an ad using sample code provided by Facebook: https://raw.githubusercontent.com/facebook/facebook-php-business-sdk/6792f3c636875af0c5bef921d17729af30b1c15a/examples/adgroup_creation.php

Up to 5 steps are working, but 6 th step `adCreavive` not working. It always gives the error "Ad Must Be Associated With a Facebook Page".

If I set AdCreativeFields::OBJECT_ID it gives a different error.

--0--

I try with another sample code provided here: https://developers.facebook.com/docs/marketing-api/buying-api for creating adCreative.

This gives an error saying that my App is in development mode. Since I just created my app and it not submitted for review.

Someone help me to proceed next.

**Comment by effetb** [comment]
Hi, same issue here.

The examples are completly broken and I just can't find how to create an ad properly... What a waste of time. Can you please update the examples to match the new code ?? I use the v3.0 branch

**Comment by palpalani** [comment]
Now, I am able to create ads. 

Using this document: https://developers.facebook.com/docs/marketing-api/buying-api and now API asking to Instagram account, for that, I use this help: https://stackoverflow.com/a/44054867

**Comment by effetb** [comment]
Thank you ! I managed to publish ads but I wasn't able to save the ad creative. It seems that the only difference was in the ad creation, i was using the creative object

````php

$ad_id = null;

$ad = new Ad($ad_id);
$ad->setParentId($account_id);
$ad->setData(array(
	AdFields::NAME     => 'My Ad',
	AdFields::ADSET_ID => $adset_id,
	AdFields::CREATIVE => $creative,
	AdFields::STATUS   => \FacebookAds\Object\Values\AdStatusValues::PAUSED
));
```` 

instead of that 

````php
	AdFields::CREATIVE => array('creative_id' => $creative_id),

````

**Comment by jingping2015** [comment]
Please take look the example here https://developers.facebook.com/docs/marketing-api/reference/adgroup/
