### ISSUE TITLE
Call to undefined method FacebookAds\Object\Page::getLeadGenForms()

### ISSUE THREAD

**Issue by Naoow** [facebook/facebook-php-business-sdk#455]
Tried to test the code from this page to get the lead forms
https://developers.facebook.com/docs/marketing-api/guides/lead-ads/retrieving

`use FacebookAds\Object\Page;

$page = new Page(<PAGE_ID>);
$leadgen_forms = $page->getLeadgenForms();`

Got error: Call to undefined method FacebookAds\Object\Page::getLeadGenForms()

I guess the function getLeadGenForms() is not working anymore?

Thanks!

**Comment by giorrrgio** [comment]
The `getLeadgenForms` method is missing, and I think it should be there. It was removed in 9cd1670f90986b11e20f2f014b62cc4e164b7131

**Comment by ekawalec** [comment]
Any changes?? Stil missing :((

**Comment by khaledelmahdi** [comment]
Any update about this?

**Comment by jingping2015** [comment]
This undefined method problem should be fix in our next release.

**Comment by vicdus** [comment]
Already in most recent release https://github.com/facebook/facebook-php-business-sdk/blob/master/src/FacebookAds/Object/Page.php#L3237
