### ISSUE TITLE
While creating ad we get => "Instagram Account Is Missing" | But we never used instagram!!! How to provide page instead?

### ISSUE THREAD

**Issue by aarefjev** [facebook/facebook-php-business-sdk#464]
This is a very basic sample code  on your latest SDK using your latest API version and it's impossible to create an Ad with those settings.

`
try {

    Api::init(
        FB_APP_ID,
        FB_APP_SECRET,
        FB_ACCESS_TOKEN
    );

    $account_id = 'act_1494809393962075';
    $adset_id = '23843004379660212';
    $page_id = '123118179545';

    $image = new AdImage();
    $image->setParentId($account_id);

    $image->{AdImageFields::FILENAME}= "ad_test.png";
    $image->create();

    echo 'Image Hash: '.$image->hash . "\n";

    $link_data = new AdCreativeLinkData();
    $link_data->setData(array(
        AdCreativeLinkDataFields::MESSAGE => 'try it out',
        AdCreativeLinkDataFields::LINK => 'http://www.ask.com',
        AdCreativeLinkDataFields::IMAGE_HASH => $image->hash,
    ));

    $object_story_spec = new AdCreativeObjectStorySpec();
    $object_story_spec->setData(array(
        AdCreativeObjectStorySpecFields::PAGE_ID => $page_id,
        AdCreativeObjectStorySpecFields::LINK_DATA => $link_data,
    ));

    $creative = new AdCreative();
    $creative->setParentId($account_id);
    $creative->setData(array(
        AdCreativeFields::NAME => 'Sample Creative',
        AdCreativeFields::OBJECT_STORY_SPEC => $object_story_spec,
    ));

    $creative->create();
    echo 'Creative ID: '.$creative->id . "\n";

    $ad = new Ad();
    $ad->setParentId($account_id);
    $ad->setData(array(
      AdFields::CREATIVE =>array('creative_id' => $creative->id),
      AdFields::NAME => 'My First Ad',
      AdFields::ADSET_ID => $adset_id,

    ));

    $ad->create();
    echo 'Ad ID:' . $ad->id . "\n";
    
} catch (\Exception $e) {
    print_r($e);
    echo 'Error User Title: ' .$e->getErrorUserTitle() .PHP_EOL;
    echo 'Error User Message: ' .$e->getErrorUserMessage() .PHP_EOL;
                
                
    die("Error Occured!");
}`

**Comment by aarefjev** [comment]
Right the full error message said:

Error User Title: Instagram Account Is Missing
Error User Message: You're using Instagram as a placement. Please select an Instagram account to represent your business in your Instagram ads, or select a Facebook Page to use instead.

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
