### ISSUE TITLE
Do you realize that your samples don't work on APi version 3.0? Right?

### ISSUE THREAD

**Issue by aarefjev** [facebook/facebook-php-business-sdk#466]
Do you realize that your samples don't work on API version 3.0.5? Right?
To be more specific - Ad creation.

**Comment by AmyHSW** [comment]
Hi, we've published new sample code for many api including ad creation. Please let us know if the new sample code does not work for you. Thanks!

**Comment by jingping2015** [comment]
Do you mean the sample code in readme ? #419 have a fix which maybe helpful to unblock you.
Also the fix should be available for next release.
