### ISSUE TITLE
(#100) social_impressions is not valid for fields param - When pulling ad insights.

### ISSUE THREAD

**Issue by balatin** [facebook/facebook-php-business-sdk#469]
Hi there,

When trying to pull ad insights I get the following message. And below that is my implementation:

**(#100) social_impressions is not valid for fields param**

`$fields = (new AdsInsights())->getFields();
      $insights = $ad->getInsights($fields, array('time_increment' => $increment, 'time_range' => array('since' => $since, 'until' => $until)));`

Locally I just removed that social_impressions from AdsInsightsFields.php file and that worked.

**Comment by Hydroxi** [comment]
Thanks for the fix!

**Comment by jingping2015** [comment]
This issue will be fix in our next release. Thanks for reporting it.
