### ISSUE TITLE
locked at 2.5.2

### ISSUE THREAD

**Issue by teamMason** [facebook/facebook-php-business-sdk#470]
I need to use version 3.0 because accordin  with Facebook Documentation, version 2.12  has some field and endpoints deprecated, Inside of Ad sets fields I need change IS_AUTOBID for BID_STRATEGY but is only available from the  version 3.0 of your SDK wich is locked accordin with composer.

**Comment by jingping2015** [comment]
Can you give me context or sample code for this ?

**Comment by teamMason** [comment]
I could resolved it, when you try to install the application adding the
library inside of composer.json thos message is shown, I fixed it
installing directly with composer require facebook/php-business-sdk": "3.0.0
"

**Comment by teamMason** [comment]
This error happens when I include the library inside of composer.json.
I resolved it using:  composer require facebook/php-business-sdk": "3.0.0"

**Comment by jingping2015** [comment]
Cool! then I am going to close this issue.
