### ISSUE TITLE
I'm getting  (#2) Service temporarily unavailable but service seems to be working

### ISSUE THREAD

**Issue by QSoto** [facebook/facebook-php-business-sdk#474]
The error below suggests the service is unavailable, https://developers.facebook.com/status/ suggests other wise.

I have tried this over around 4 hours and am still hitting this error, the code is as simple as the code below, feels like something else may be going on.

```
public function getActiveAds(){
		$account = new AdAccount('act_' . self::FB_ACCOUNT_ID);
		$fields = array(
		    CampaignFields::ID,
                    'effective_status'
		);
		$params = array(
		    'effective_status' => array(
		        Campaign::STATUS_ACTIVE
		    ),
		);

		$campaignSets = $account->getCampaigns($fields, $params);
		return $campaignSets;
	}

getActiveAds();
```

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
