### ISSUE TITLE
Account Insights Breakdown By Country Brings Back Wrong Numbers

### ISSUE THREAD

**Issue by gelinger777** [facebook/facebook-php-business-sdk#479]
I am trying to get our ad account spend by country for specific day(yesterday) . But from the API I am getting totally wrong numbers than in the ad acount dashboard. What could be the reason? 

 ```
$fields = array(
                    'spend', 'account_currency'
            );
 $params = array(
                'breakdowns' => array('country'),
            );
     
                $params['date_preset'] = 'yesterday';
         

                $stats = (new AdAccount('act_'.$account_id))->getInsights(
                    $fields,
                    $params
                )->getResponse()->getContent();
```

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
