### ISSUE TITLE
AdImageFields missing FILENAME

### ISSUE THREAD

**Issue by mikeho** [facebook/facebook-php-business-sdk#480]
In this most recent commit and 3.1.2 release (68a36ad8f63acca96866ac9b5e4478d6dc137200), it appears that FILENAME (among a few other fields) were removed from src/FacebookAds/Object/Fields/AdImageFields.php.

However, according to the most recent API docs, "FILENAME" is still a valid field for AdImage, and it's even highlighted in the very first/topmost example:

https://developers.facebook.com/docs/marketing-api/reference/ad-image

Why was FILENAME removed?

**Comment by vicdus** [comment]
This will be fixed in next release.
