### ISSUE TITLE
AdImageFields::BYTES gone

### ISSUE THREAD

**Issue by felixlehmann** [facebook/facebook-php-business-sdk#482]
After updating from
facebook/php-business-sdk (3.1.1)
to 
facebook/php-business-sdk (3.1.2)
the field `bytes` in AdImageFields is gone.

Couldn't find any hint on https://developers.facebook.com/docs/marketing-api/reference/ad-image/ that it's deprecated.

Can we get it back please? :)

**Comment by vicdus** [comment]
This will be fixed in next release.
