### ISSUE TITLE
Duplicated deleteAdMIns() in Page.php

### ISSUE THREAD

**Issue by Surf-N-Code** [facebook/facebook-php-business-sdk#484]
There is duplicated functions within the Page class called: deleteAdMIns() & createAdMIn().
Also, it is spelled strangely.

**Comment by cmorbitzer** [comment]
Same issue here. Throws ` Symfony\Component\Debug\Exception\FatalErrorException · Cannot redeclare FacebookAds\Object\Page::deleteAdMIns() `

**Comment by vicdus** [comment]
Thanks for reporting. This will be fixed in next release

**Comment by AnonymousArthur** [comment]
@vicdus This happens to 3.1.2, 3.1.3 and 3.1.4.
3.1 and 3.1.1 seems like free of this issue.

**Comment by abju** [comment]
@vicdus When next release?

**Comment by jingping2015** [comment]
This already be solved in our recent release. Thanks for reporting this issue.
