### ISSUE TITLE
field 'id' is required in getBusinesses method

### ISSUE THREAD

**Issue by carlosbuzato** [facebook/facebook-php-business-sdk#486]
Hello, I'm trying to execute the method getBusinesses from the User class. But I'm getting the next error:
"Field 'id' is required".

Take a look on the code below:
`$fields = array(
            UserFields::ID => id123,
            UserFields::TOKEN_FOR_BUSINESS => 'accesstoken',
        );

        $User = new User();
        $myBusiness = $User->getBusinesses($fields);`

May you help? Pls!!

**Comment by vicdus** [comment]
Hi,
the user constructor need id as parameter, like `$usr = new User(123);`


Also don't upload access token - it should be treated as credentials like a username&password

**Comment by vicdus** [comment]
Please log out immediately to invalid your access token
