### ISSUE TITLE
CampaignFields::SPEND_CAP return null for all campaigns, help-me!! 

### ISSUE THREAD

**Issue by carlosbuzato** [facebook/facebook-php-business-sdk#487]
Hi, i'm trying return SPEND_CAP value for my campaigns, but all of then are returning null. Take a look on the following code: 

`$fields = array(
CampaignFields::NAME,
CampaignFields::OBJECTIVE,
CampaignFields::SPEND_CAP,
);

$AdAccount = new AdAccount(<ACT_ID>);
$cursor = $AdAccount->getCampaigns($fields);

foreach ($cursor as $campaigns) {
dump($campaigns->{CampaignFields::NAME}.PHP_EOL);
dump($campaigns->{CampaignFields::OBJECTIVE}.PHP_EOL);
dump($campaigns->{CampaignFields::SPEND_CAP}.PHP_EOL);
}

$cursor->fetchAfter();`

What is the possible solution for this problem?

**Comment by jingping2015** [comment]
Did you try with curl API call? If the curl API call have same result, it means this is a API bug, please  report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!

**Comment by carlosbuzato** [comment]
> Did you try with curl API call? If the curl API call have same result, it means this is a API bug, please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!

Thanks man!
