### ISSUE TITLE
Deprecations with `strlen` on null. 

### ISSUE THREAD

**Issue by przepompownia** [facebook/facebook-php-business-sdk#565]
I'd like only to upgrade this library to work with PHP 8.1 (it works with 8.0, other person can verify it on the FB side). I don't want to create any personal FB account to resolve the below problem. 

In https://github.com/facebook/facebook-php-business-sdk/blob/main/src/FacebookAds/Object/ServerSide/CustomData.php#L462 `normalize()` fails on null values. To reproduce, in https://github.com/facebook/facebook-php-business-sdk/blob/main/src/FacebookAds/Object/ServerSide/CustomData.php#L462 set some value to null and observe deprecation warnings.

```
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in .../facebook-php-business-sdk/src/FacebookAds/Object/ServerSide/CustomData.php on line 462
``` 

It matters on environments where such errors are converted to exceptions.

**Comment by stcheng** [comment]
@natewiebe13 thanks for addressing this issue. the corresponding PRs will be merged after this thanksgiving holiday.

**Comment by przepompownia** [comment]
Thank you @stcheng What do you think about tag this commit?

**Comment by natewiebe13** [comment]
There were also deprecations fixed in the codegen repo. If we get a new tag before v16, hopefully the codegen changes get imported for that tag as well.
