### ISSUE TITLE
getDefaultRequestHeaders() is misspelled as getDefaultRequestHeaderds()

### ISSUE THREAD

**Issue by ricky-cortopassi** [facebook/facebook-php-business-sdk#569]
# Facebook PHP Business SDK Issue

https://github.com/facebook/facebook-php-business-sdk/blob/main/src/FacebookAds/Http/Client.php#L128

getDefaultRequestHeaderds() ( current ) 
getDefaultRequestHeaders() ( expect it to be )

**Comment by natewiebe13** [comment]
This code is actually pulled in from the codegen repo. I've made a PR there: https://github.com/facebook/facebook-business-sdk-codegen/pull/60
