### ISSUE TITLE
PHP 8.1 Deprecation

### ISSUE THREAD

**Issue by davidistores** [facebook/facebook-php-business-sdk#570]
# Facebook PHP Business SDK Issue
Since we want to handle bugs more efficiently, we've decided to close issue reporting in Github and move to our dedicated bug reporting channel.
If you encounter a bug with Business SDK (PHP), please report the issue at [our developer bug reporting channel](https://developers.facebook.com/support/bugs/).

At this file src/FacebookAds/Object/AbstractCrudObject.php
inside the __constructor you are using default valuue "null" for $id that throwing php 8.1 error while trying execute strpos() on null on Line 64

Please change the default vlaue to empty string I guess
thanks alot
![issue-screen-2](https://user-images.githubusercontent.com/122877913/212882692-ea27e752-d529-4c29-bfb3-460287561724.png)
![issue-screen-1](https://user-images.githubusercontent.com/122877913/212882697-ed1325fd-1ad7-4751-b7a1-11b8a9503098.png)

**Comment by davidistores** [comment]
How can I resolve it vai composer ?

**Comment by natewiebe13** [comment]
Since it's ultimately a fix from another repo, I'd probably tackle it by using patches. If you wanted a purely composer way to do it, I'd probably recommend https://github.com/cweagans/composer-patches

**Comment by stcheng** [comment]
The latest version has fixed this issue. Thanks.
