### ISSUE TITLE
Union types are only allowed since php8

### ISSUE THREAD

**Issue by chengshanmu** [facebook/facebook-php-business-sdk#576]
syntax error, unexpected '|', expecting ';' or '{',
\vendor\facebook\php-business-sdk\src\FacebookAds\Cursor.php,438

public function current() : AbstractObject|bool {

**Comment by natewiebe13** [comment]
See: https://github.com/facebook/facebook-php-business-sdk/pull/572#issuecomment-1423208117

Since then, composer.json has been updated with php >=8 as a version constraint, so this is correct.

**Comment by chengshanmu** [comment]
thanks
