### ISSUE TITLE
Syntax error in FB version v16.0.0

### ISSUE THREAD

**Issue by nitin-aika09** [facebook/facebook-php-business-sdk#587]
# Facebook PHP Business SDK Issue
This issue seems to be with SDK specific. Issue seems to be at AbstractObject|bool at this line: https://github.com/facebook/facebook-php-business-sdk/blob/main/src/FacebookAds/Cursor.php#L438

```public function current() : AbstractObject|bool {
    return isset($this->objects[$this->position])
      ? $this->objects[$this->position]
      : false;
  }
```

Error Response
```
{
    "message": "Parse error: syntax error, unexpected '|', expecting ';' or '{'",
    "code": 0,
    "file": "/application/vendor/facebook/php-ads-sdk/src/FacebookAds/Cursor.php",
    "line": 441
}
```

Could you please check and make a fix for that.

**Comment by hakimio** [comment]
You have to upgrade your PHP to v8.
