### ISSUE TITLE
The AdAccountFields enum does not currently implement the ACCOUNT_STATUS field.

### ISSUE THREAD

**Issue by iamyukihiro** [facebook/facebook-php-business-sdk#588]
It appears that the `AdAccountFields` enum does not currently implement the `ACCOUNT_STATUS` field. When examining the API response, it provides values such as "0" and "1," which are equivalent to the values in `FacebookAds\Object\Values\AdStatusValues` and `FacebookAds\Object\Values\CampaignStatusValues` . However, there is no implementation for `FacebookAds\Object\Values\AdAccountStatusValues` , which can be confusing for developers as it lacks explicit representation.

I kindly request that you consider implementing `FacebookAds\Object\Values\AdAccountStatusValues` to provide clarity and consistency for developers. Your attention to this matter would be greatly appreciated.

**Comment by stcheng** [comment]
Currently, we are using the 'unsigned int' type to indicate account status, while for campaigns, ads, and similar implementations, we are utilizing an enum. Therefore, implementing this change will pose a limitation for us.
