### ISSUE TITLE
OpenSSL SSL_connect: Connection reset by peer in connection to graph.facebook.com:443 Error

### ISSUE THREAD

**Issue by metehan346** [facebook/facebook-php-business-sdk#603]
Hello everyone.

I want to use Facebook Conversion API. But I usually get this error in Conversion API requests:
FacebookAds\Exception\Exception #35
OpenSSL SSL_connect: Connection reset by peer in connection to graph.facebook.com:443

But sometimes it works fine. (very interesting)
Do you have any advice about this problem?

Thank you.

PHP Version: PHP 8.1
OpenSSL Version: 3.0.2

![Adsız2](https://github.com/facebook/facebook-php-business-sdk/assets/165680472/2c9fbfa6-9f14-48f2-905d-75e955880ea3)

**Comment by stcheng** [comment]
what's the exception and the error?
