### ISSUE TITLE
Incorrect PHPDoc types

### ISSUE THREAD

**Issue by stefanfisk** [facebook/facebook-php-business-sdk#605]
This causes PHPStan to generate errors like "Parameter #1 $user_data of method FacebookAds\Object\ServerSide\Event::setUserData() expects FacebookAds\Object\ServerSide\FacebookAds\Object\ServerSide\UserData, FacebookAds\Object\ServerSide\UserData given.PHPStan".

According to https://github.com/facebook/facebook-php-business-sdk/issues/new I should raise this issue at https://developers.facebook.com/support/bugs/. According to https://developers.facebook.com/support/bugs/ I should raise the issue in the [Developer Community Forum](https://developers.facebook.com/community?sort=trending&category=2173834726268374&from_bug_tool=true). The form to post a new question just errors out with the message `error performing query`.

This does very much feel like screaming into the void...

**Comment by stefanfisk** [comment]
Just realized that someone opened #551 for this over two years ago...

**Comment by stefanfisk** [comment]
And that #545 was opened three years ago...

**Comment by stcheng** [comment]
thanks @geoffreyrose !
