### ISSUE TITLE
[README.md] fix typo

### ISSUE THREAD

**Issue by truongd3** [facebook/facebook-php-business-sdk#610]
# Facebook PHP Business SDK Issue
Fix typo errors in [README.md](README.md) and [CHANGELOG.md](CHANGELOG.md)

#### README.md
1. **Missing Dollar Sign for Variable**
In the [**Create Objects**](https://github.com/facebook/facebook-php-business-sdk/blob/main/README.md#create-objects) section, the `AdSetFields::CAMPAIGN_ID` is missing a `$` before `campaign_id`

2. **Code Block Syntax Highlighting**
Add `shell` tag for [second code block line 335](https://github.com/facebook/facebook-php-business-sdk/blob/main/README.md#debug)

#### CHANGELOG.md
1. **Missing Parenthesis for Link Attachment**
In the [**Unreleased v11.0.0**](https://github.com/facebook/facebook-php-business-sdk/blob/main/CHANGELOG.md#v1100), the link attached is missing a pair of parenthesis

**Comment by stcheng** [comment]
Hi @truongd3 would you mind submit a PR to address the issues?

**Comment by truongd3** [comment]
Dear @stcheng , thank you very much for allowing me to submit a PR! I tried but it said my permission is denied. Can you please let me know what I should do?

**Comment by truongd3** [comment]
Hi @stcheng , this is my [PR](https://github.com/facebook/facebook-php-business-sdk/pull/611). Have a great day!
