### ISSUE TITLE
composer update error

### ISSUE THREAD

**Issue by weijunken** [facebook/facebook-php-business-sdk#614]
When I updated to the latest version, the following error occurred :
    
- facebook/php-business-sdk 21.0.0 requires facebook/php-capi-param-builder 0.1.0-dev -> could not be found in any version, there may be a typo in the package name.

**Comment by jcadsmurai** [comment]
Same issue here. This [commit](https://github.com/facebook/facebook-php-business-sdk/commit/69f2310839f56325e310fb0bcf4cdae11f74c401) introduces a new dependency that isn't publicly available, which causes problems. Additionally, the package is marked as `dev`, leading to conflicts for projects with a `minimum-stability` set to `stable` in their `composer.json`.

**Comment by liliarizona** [comment]
@weijunken @jcadsmurai  thx for raising the issue, we have release version 21.0.1 that fixed the issue. Could you try installing again?

**Comment by liliarizona** [comment]
Closing the thread as fix released. Feel free to re-open if issue recurs.
