### ISSUE TITLE
Business Api createVideo param check issue

### ISSUE THREAD

**Issue by zcmk123** [facebook/facebook-php-business-sdk#622]
https://github.com/facebook/facebook-php-business-sdk/blame/95e518052e11ae4239e59b26ca93290371aa719f/src/FacebookAds/Object/Business.php#L3377

video_file_chunk => 'string'

seems sdk cannot get file

upload fail.

i change code to video_file_chunk => 'file', then upload success, is this a bug?

**Comment by bastien-effetb** [comment]
Hello, could you please share the code you are using to upload videos ? It's not working at all for me and It would be very helpful for me. Thank you
