### ISSUE TITLE
Support batch requests

### ISSUE THREAD

**Issue by bjeavons** [facebook/facebook-php-business-sdk#77]
Any plans to support [batched requests](https://developers.facebook.com/docs/marketing-api/batch-requests) using the Facebook Ads SDK?

**Comment by greggles** [comment]
I would also like this.

**Comment by monitotxi** [comment]
+1

**Comment by facebook-github-bot-1** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by foxpcteam** [comment]
any news?

**Comment by bjeavons** [comment]
I didn't see it before but v2.5 of the SDK supposedly supports batch requests: https://developers.facebook.com/docs/php/howto/example_batch_request

**Comment by allentsai** [comment]
Just running into this with our integration, would be nice to have.  For now, we might be writing our own curl wrapper...

https://developers.facebook.com/docs/marketing-api/batch-requests/v2.5

**Comment by Mattin** [comment]
I think batch requests are already in, I'm using it from v2.4 (for ads and insights download/import). For what exactly you want them?

**Comment by neok** [comment]
@Mattin for creating AdSets, Ads, AdCreatives

**Comment by ryancwalsh** [comment]
Is it true that facebook-php-ads-sdk doesn't support batch requests? (That's what http://stackoverflow.com/a/32530905/470749 says.) 

Then why does the Ad object have a [`$pending`](https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/Ad.php#L165) param in `public function getInsights(array $fields = array(), array $params = array(), $pending = false)`? What does that allow? 

I really just want to be able to grab insights for all active ads (across *all* campaigns within an account). The Insights edge doesn't seem to allow filtering by ads status, so I thought my approach would be to run 1 query to grab the IDs of all active ads and then run a batch of Insights queries (get the insights for each ad).

What would you recommend?

**Comment by ryancwalsh** [comment]
@paulbain Can you or someone please point us in the right direction? This has been open since Mar 2015. I think batch requests in the PHP Ads SDK would be great. Thanks!

**Comment by storm23** [comment]
https://developers.facebook.com/docs/php/howto/example_batch_request/

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.

**Comment by greggles** [comment]
Not sure if this was a bulk close or if your comment was specific to this issue. I did a quick search and the page on [async requests](https://developers.facebook.com/docs/marketing-api/asyncrequests) linked in the opening comment now has examples of using AdAsyncRequestSet, so it seems this is indeed fixed.

Thanks for your work!
